== Introduction.

In preparing for publication the following Memoirs of Sarah Harrison`'s life and travels,
we have been aware of the sentiment alluded to by Job Scott,
that "`some think there are Journals enough printed.`"
But, with him,
we likewise can say we have no "`idea that so many were or would be published,
as to render any more useless.`"
We are rather of the mind, with George Dillwyn,
that "`the Journals of pious persons are some of the safest
writings that can be put into the hands of young people,
though they may contain little more than a recital
of the ways in which those worthies were led,
and the difficulties which, by a simple attention and obedience to their heavenly Guide,
they surmounted.
They are, however, not likely to be very interesting to any but such as have their feet,
in some degree, turned into the same way.
If to those who seek more for amusement than instruction, they are insipid,
it is because they invite to a path which persons of that
class are more inclined to avoid than to travel.`"

As Sarah Harrison kept no regular Journal, the accounts here presented,
have been gleaned from her letters and detached memorandums.
Her literary acquirements appear to have been very limited,
and her hand-writing often scarcely legible; but the energies and dedication of her mind,
may in some degree be discovered,
by the brief narratives and reflections which she occasionally penned.
The way in which she was led, and some of "`the difficulties which,
by a simple attention and obedience to her heavenly Guide,
she surmounted,`" may be interesting to some who "`have
their feet in some degree turned into the same path.`"
Should this be the case,
the labour of gathering up these fragments will be in some measure answered.
