== Chapter I

Sarah Harrison, daughter of Rowland Richards of Lower Providence, then Chester,
now Delaware county, Pennsylvania, was born in or about the year 1736.
Her natural disposition was rather volatile, by reason of which,
and the habits of lightness and vanity incident to unthinking youth,
she underwent much suffering and mental conflict,
before she became willing to yield to manifested duty.
Of the early period of her life she afterward made these remarks:

In my youthful days, I gave way to things that proved a snare to me,
and caused me many sorrowful days and nights, yea, months and years,
before I witnessed reconciliation with my God;
and I now stand as a monument of his mercy.
All unrighteousness is sin; and the wages of sin is death.
This I know by sorrowful experience;
for it brought death upon the innocent life of God in my heart,
and made me a long wilderness travel.
I too lightly esteemed the early visitations of God to my soul,
until I became somewhat like the deaf adder that would not hear the voice of the charmer,
though he charmed ever so sweetly.

But in these my young years, when I was flying away as upon the wings of vanity,
the Lord was pleased to meet with me in a narrow place,
where I saw there was no way for me to escape his righteous judgments,
either here or hereafter.
I was led deeply and awfully to consider the woeful consequence
of my sins being brought to judgment after death,
where there was no remedy; and I was made willing to bear his indignation,
because I knew I had sinned against him many a time,
though in what the world calls little things,
yet I was convinced they were great enough to exclude me from the Divine presence forever,
if I did not repent, and endeavour to walk more circumspectly.
I can with thankfulness say, that the awful impressions that were then made on my mind,
have never been erased: no; they were too deep for any blast of temptation to blow away.

Having thus been visited with the judgments of the Lord for disobedience and transgression,
although, blessed be his great name, they were mixed with adorable mercy;
and having thus tasted of the terrors of the Lord for sin,
suffer me to exhort the dear youth to watch and be sober,--to stand in awe, and sin not;
that so you may escape the righteous indignation of God,
which will be revealed sooner or later against all
the vanities of this wicked and deceitful world.

About the twent year of her age she was married to Thomas Harrison,
of the city of Philadelphia.
In her domestic department, she was industrious, managing and neat;
as a friend and neighbour, kind and obliging;
of extensive charity and tender feeling toward the poor and needy,
many of whom received daily supplies from her hand.
Her house for many years was an asylum for the oppressed,
especially the people of colour;
her husband being a warm and indefatigable advocate for their emancipation and improvement.

She had ten children, most of whom died in their infancy,
and only two of that number lived to be men.
Those only who have witnessed the trial of parting with
their tender offspring in the days of their innocence,
can fully enter into the feelings of the fond parent on such occasions.

She had a lively and acceptable gift in the ministry,
and was much concerned for the prosperity of Truth, and the welfare of society.
For this purpose she was frequently engaged in religious visits,
of which she sometimes made memorandums.

About the beginning of the 9th month, 1787, she left home,
in company with Lydia Hoskins and Norris Jones,
on a religious visit to the southern states; of which she says:

On our way we were at Lampeter meeting,
in which Lydia Hoskins was favoured with strength to warn the unruly,
and stir up the pure mind in some of the careless.
Next day we were at the week-day meeting at Lancaster,
in which several Friends who were in company with us had good service.
Having let in discouragements, by the imprudence of others,
I passed through several meetings in silence, and left them burdened in mind:
but at length gave up to be willing to do what I could;
and blessed be the name of the everlasting Counsellor,
he has been a guide to my perplexed thoughts,
and a cordial to my dejected spirits.--I have seen light rise out of obscurity,
and darkness to become as the noon-day.
Although I have not had much to say,
and what has been given me has sometimes been very close,
yet I believe it has been well taken, and I have therein found peace.

Sarah Harrison appears to have been one who thought so much
of dreams as frequently to repeat them to others.
And as those who lay much stress on dreams, as omens, or Divine communications,
are very liable to fall into a habit of making interpretations,
either of their own sleeping imaginations,
or of the dreams of others related to them--so Sarah Harrison was sometimes subjected
to trouble and unhappiness arising from this (too often) imaginary source.
Very soon after she had set out on this concern to
make a religious visit to the southern states,
a letter was imprudently sent after her that afflicted her very much;
so that she had thoughts of returning home immediately.
On which occasion she wrote thus:
"`The state of my mind was such as could not be described; but this I may say,
that the enemy magnified himself, and rejoiced over me,
insinuating that I could do God no service,
and was also running my husband to great expense to no purpose.
So I thought best for me to go home, and mentioned it to my companion in the evening,
intending the next morning to return home, if my mind was not more composed;
and which I believe I should have done,
had not the sun of righteousness arisen and dispelled the cloud,
giving me to see that it was the work of the enemy to lay waste,
and discourage me from attending to my duty;
and the letter that I had received was but a messenger of Satan sent to buffet me.`"
To which she adds this salutary wish,
"`Oh! that Friends would be careful how they put forth a finger, at such times,
to unsettle the minds, of those who are under such, weighty exercises!`"

Much of this trouble, it seems, was occasioned by telling a dream;
and a friend shortly after wrote to her, saying,
"`I was sorry to hear thou opened that dream before thou left home;
especially as it turned out to afflict thee so much, I thought without a cause.`"
To which this cautionary wish may be added,
Oh! that Friends would be careful how they suffer their minds to be influenced by dreams,
so as to lay too much stress on them;
inasmuch as they often arise from a state of indisposition, either of body or mind,
that prevents sound and tranquil sleep.
And Oh! that such as have dreams may be guarded against
a habit of frequently telling them to others,
and giving or inviting interpretations of them,
that may oftener diminish than increase their own happiness,
and the comfort of their credulous friends.

From some imperfect sketches of this journey, and reflections which she penned,
the following has been collected:

We had meetings at Middle Creek, Back Creek, Bear Garden and other places,
and so on taking meetings through Virginia,
till we came to the Yearly Meeting in North Carolina held at Centre;
which began the 27th of 10th month.
Here I felt much exercise of mind,
with desires that I might be clothed with the whole armour of light,
so that I may know what to do and what to leave undone.
Here are a large number of professors, but the life of religion appears to be very low.
There is need of skilful workmen that can divide aright;
and Oh! that the great Master may be pleased to anoint and re-anoint my eyes,
so that I may not see men as trees, but in their perfect shapes,
and be favoured with strength to speak the whole truth, and nothing but the truth.

After the Yearly Meeting, we attended New Garden monthly meeting,
also had meetings at Deep river, Springfield, Marlborough, Providence,
and to the Quarterly meeting at Cane Creek.
Here we met with William Jackson and Warner Mifflin,--Charity Cook and Rebecca Fincher.
The subject of holding mankind as slaves came weightily before this meeting,
and a committee was appointed to visit all such as have slaves,
and if they continue to disregard the wholesome advice of the body,
monthly meetings were directed to disunite them.
Warner Mifflin went to attend the Assembly of North Carolina
with a well-written petition from the Yearly Meeting.

Thence taking meetings on the way we reached Wrightsborough, in Georgia,
where we spent about four weeks and visited many of the families of Friends.
Went thence to Bush river, in South Carolina,
where we spent about a month visiting families and meetings.

While at Bush river, Sarah Harrison was several days very ill of a cholic,
and said she thought her companions would have to
leave her to lay her bones at Bush river.
"`This,`" says Norris Jones in a memorandum kept by him, "`was a close trial of our faith.
To be taken sick from home, is very trying indeed;
but to be called from works to rewards, even to the righteous, is very close work;
what then must it be to those who are unprepared!
May I improve by every memento of this kind,
which is in unerring wisdom permitted;--that so when
that solemn charge is sent to my habitation,
Steward give up thy stewardship; for thou mayest be steward no longer,--I may be ready.`"
Sarah Harrison adds: "`When we left Bush river,
it was a solemn parting with Friends of that neighbourhood.
That peace which passeth all human understanding was felt,
so that I thought it a full compensation for all I had passed through.`"

In this journey from Bush river to Charleston,
they travelled about one hundred and sixty miles.-- Norris Jones says,
"`The second night we reached a little cabin,
where one bed was procured for Sarah Harrison and Lydia Hoskins;
I with one friend slept in the wagon; the rest slept in the woods.
The next night our fare was no better--and the third
we could get but one bed for the women,
the rest of us slept on the floor.
But we travelled in much unity, carrying our provisions with us.`"

Sarah Harrison writes:

In the beginning of the 3rd mo., 1788, we reached Charleston,
being accompanied by Isaac Cook and John Wilson,
appointed by Bush river monthly meeting to visit the few Friends in Charleston,
concerning their being joined to that meeting,
agreeable to the direction of the Yearly and Quarterly meeting.
A few young men, but no female members, reside in Charleston.
In this town we tarried about four weeks, and had many meetings;
most of which were laborious, exercising times, yet I trust they ended well,
though several were silent,
in others the power of Truth was felt to be above every other power.
Great has been the oppression we have felt here;
the gospel truths we have had to deliver being so repugnant
to the disposition of the minds of most of the inhabitants,
who, like many others, love ease, and don`'t want their false rests disturbed.
They say much against slave-holding;
all we have conversed with agree that it is not right
to hold their fellow creatures in bondage,
and wish they were all free, declaring that they are only a burden to them.
But when any thing is said to promote their freedom,
they soon turn and say they are not fit for freedom,
because they are such poor helpless creatures.
But Oh! that God may be pleased to hasten the coming of
that day when the eyes of them that see shall not be dim,
and the ears of them that hear shall hearken to his inspeaking voice.

3rd mo.
27th. Yesterday was at a small meeting in Charleston,
when the states of those present were laid open before them, I trust in a clear light,
though not with enticing words of man`'s wisdom.
I often think I am one of the most stammering speech
of any that ever were sent forth on such an errand.
May he that promised to be with the mouth of Moses, be with me at all times,
especially when engaged in his cause, and teach me what I shall say,
is the desire of my heart; that so his great name may be exalted,
and self may be abased in me.

Although the Lord has been pleased at times to lead
me through the valley and shadow of death,
yet there has been times when I could sing praises to his name,
and extol him that rideth upon the heavens.--But notwithstanding I have
been favoured at times to taste and see the fruit of the valleys,
I have not been exempted from winter`'s pinching cold, and summer`'s scorching heat;
insomuch that at seasons, it seemed as if this earthly tabernacle must be dissolved:
but these trials were removed when the sun of righteousness
arose as with healing under his wings.

From Charleston they went by way of Pedee, Core Sound, Newbern, Contentney, Jack Swamp,
Rich Square, and to the Yearly Meeting held at Blackwater in Virginia.
Thence back to North Carolina, and after visiting the remaining meetings there,
returned to Virginia.
Norris Jones says,
"`We have been engaged in visiting slaveholders
in the verge of Black-water monthly meeting,
and have the satisfaction to see the labour blessed,
so that near fifty of that oppressed people were manumitted in our presence.
The power of Truth was livingly felt in many of these
opportunities to our humbling admiration.`"

Norris Jones also gives the following account of their visits
to slaveholders in North Carolina and Virginia:

6th mo.
6th. At Piney-woods meeting, which was large, Sarah Harrison had close work,
and again touched on slave-holding.
In the afternoon, we met by accident a Friend who held twenty-three slaves.
The subject was seriously gone into; and he, being reached by the power of Truth,
was prevailed upon to manumit them, to the rejoicing of the hearts of many,
and to the peace of his own mind.`"

7th. We had a close, searching opportunity with E. W. about his slaves,
and left him to consider of it.
Thence went to J. Newby`'s--he, his wife, and sister manumitted two slaves.

8th. At Old Neck meeting, which was very large.
Thomas Saint, Lydia Hoskins and Sarah Harrison appeared in testimony;
the last in a most singular, close, searching manner to the foremost rank.
After dinner, had a memorable time with the slaveholders.
After charging and silencing one Friend who held sixteen,
the power of Truth so fastened on him, that the devil was cast out by prayer and fasting;
and, after a time of silence,
he gave up freely--and two other persons also set four free.

9th. We had a full opportunity with a widow and family where we lodged,
and some of her neighbours.
The power of Truth being present, her son set his two negroes free.
From thence to J. N.`'s, and his brother set four negroes at liberty.

10th. Went to see a slaveholder,
and had an opportunity of four hours;--and we left him a slaveholder.
I wrote two manumissions for ten, and left with him in hope he would sign them.
Next day at Old Neck week-day meeting, Sarah Harrison had close, searching work again;
dined at Thomas Saint`'s; afterward called at J. J`'s, and he manumitted ten negroes.
The day following, after attending Piney-woods weekday meeting,
we went to see a slaveholder, who, after much labour with him,
manumitted his three slaves.

13th. We visited five families; four of whom were slaveholders;
and close searching work we had with them.
One Friend and his wife manumitted five slaves.
It hath been a laborious week;
but we have cause to believe the power of the Most High hath been with us,
even to the pulling down of the strongholds which sin and Satan have made.
We have now finished in North Carolina.

14th. Set out for Virginia, accompanied by a number of Friends;
and next day were at Somerton meeting.
Next morning, parting with our kind Carolina friends, we went to Johnson`'s meeting;
sat in silence about two hours,
a laborious exercising time! then Sarah Harrison spoke about one hour,
to the arousing of some, I hope.
May it fasten as a nail in a sure place.
Thence to Black Creek and Stanton meetings.
Much expectation after words.
Alas! how few are acquainted with true, silent waiting, in this, called gospel day!
I was taken with a chill in meeting, followed by a smart fever; but could say with David,
"`Thy rod and thy staff, they comfort me.`"
My dear friend, Sarah Harrison, came into the room where I was and sat down in solemn,
awful silence, in which she felt the spirit of prayer,
and in a solemn manner interceded on behalf of those
who had left everything near and dear in this life,
for the Truth`'s sake; and that the afflicted might have a few more years added,
to do the work assigned him.
My cup was made to overflow, in reflecting on the goodness of God.
I continued unwell for several days; some of the time my mind was much tossed,
and I felt, as it were, the mountains of sin and iniquity,
which I saw could not inherit the kingdom of God;
and even those things that we may compare to a grasshopper,
were felt to be a burden too heavy to bear.
But blessed be the name of Israel`'s God, he did not forsake me;
and this trying dispensation, I believe, was for the furtherance of my faith,
love and patience.
May I ever remember, that it is the humble he teacheth of his ways.

22nd. I was well enough to go with a committee of the monthly meeting of Black-water,
appointed to visit slaveholders.
We visited four; one of whom manumitted one slave, after hard, laborious work.
Next day, we went with said committee,
and visited a man and his wife who held seven slaves--a searching time it was!
Sarah Harrison appeared in awful supplication,
and prayed that the key which opened the heart of Lydia,
might be permitted to open the heart of the woman Friend present; which was granted,
and she united with her husband in setting their slaves at liberty.
I said in my heart, miracles have not ceased.
Blessed be the name of God;
and may he have the praise of his own work!--In the afternoon, we had a hard,
laborious opportunity with I. W. which lasted several hours.
A manumission was written for his slaves, but he would not sign it;
although he was fully convinced, yet the power of darkness kept him bound.
We took our leave of him and went to J. Bailey`'s to lodge.

24th. This morning the above friend, I. W. came on foot to our lodgings,
having had no rest; he brought the manumission and signed it, liberating four slaves.
A humbling time it was;--the power of Truth overshadowed us;
Sarah Harrison appeared in supplication,--and we parted with feelings of mutual joy.
Then we went to N. J.`'s. The most hardened spirit appeared in him, that we have met with.
Sarah and myself laboured with him in a very close manner;
but his heart appeared to be as hard as Pharaoh`'s:
he declared he would not sign the manumission.
So we left him, and rode to M. Baily`'s, fifteen miles; where we lodged.
Next morning, he set twenty-two free.
We then went back to N. J.`'s to try him once more; but on our first seeing him,
he appeared as determined against it as before, and said he would not do it.
We said a good deal to him, as we sat in the wagon,
and his wife desired he would set his slaves free.
At length,
the power of the Highest softened his hard heart;--he came and gave me his hand,
and was broken, even to weeping.
He asked us into his house, and we went in with him.
He then got the manumission and signed it; and truly it was a memorable time;
such as I never saw.
Sarah Harrison appeared in awful supplication: the devil was cast out, and he was broken,
as it were, all to pieces, and shed many tears; as did most or all present.

26th. We called to see a young woman who holds slaves, it being the second visit to her.
But she would not give them up;
and appeared to be one of the most hardened persons we had talked with on the subject.
Next day we had a full opportunity with a widow who held slaves.
She desired I would write a manumission; but did not choose to sign it,
till her son saw it.
We also had an opportunity with a man who holds about twenty.
He said he hoped he should see the evil of the practice.
So, after being honest with them, we left them, and went toward Burleigh.
On our way, we lodged with a slaveholder,
who appeared determined to hold them at all events.

Thence, taking divers meetings on our way, we came to Skimino,
where we met with a young man, a Friend, who held eleven slaves.
We had a satisfactory opportunity with him, and he signed manumissions for them all,
from a sense of religious duty.
Not long after, we visited a widow who was a slaveholder;
and after a laborious searching opportunity, she manumitted eleven negroes.
Next day, we had an opportunity with this widow`'s son and her granddaughter,
on the subject of holding slaves;--but alas! they set more
store by the negroes than by their right in society!
The day following we spent five hours with S. P. and his wife, steadily,
on the subject of slavery.
Being favoured with the calming influence of our heavenly Father`'s love,
they manifested more coolness than common.
At length, the power of Truth prevailed, and the wife to whom they belonged,
gave up cheerfully, and they manumitted seventeen.

In the latter end of the 7th month, we set out from Genito, to visit slaveholders.
First, to a place where the wife was willing,
but her dark-spirited husband would not comply.
Thence to his brother`'s, who after much labour, set two slaves free.
We then visited several Friends who hold slaves;
but it amounted to little more than breaking their false peace.
Next day we called to see four Friends, slaveholders; and two of them set eighteen free.
But one of them, a widow, like Lot`'s wife, looked back, and wanted the papers given up.

At Curles in Virginia, Sarah Harrison thus remarks:
"`I may with thankfulness say that I have been wonderfully
favoured with health for three months past,
and the Lord hath been graciously pleased to strengthen my inner man.
May patience have its perfect work in me.
I can with gratitude say,
I believe the arm of God`'s salvation has been made bare for our preservation thus far.`"

After taking many more meetings in Virginia, they came into Maryland,
and were at Indian Spring, Baltimore, and divers other places,
on their return to their outward habitations,
which they reached about the end of the 8th month, 1788.
