== Chapter IV

[.chapter-subtitle--blurb]
Visit to the Continent

+++[+++Sarah Harrison had now been about six years absent from her friends at home,
on this visit to England, etc. and it was natural to suppose that Friends,
both in England and at home would feel some anxiety on account
of the unusual length of time spent in this concern.
It was trying to herself, and very contrary to her inclination,
and even her expectation to be so long thus engaged--She had already
received three returning certificates from the London Yearly Meeting,
in prospect of being released; and on her return from Ireland,
in company with William Savery,
had pleasingly anticipated being ready to embark with him for her native land,
very soon after the Yearly Meeting, which William felt bound to attend.
While at Liverpool,
Sarah felt a clear impression of duty again to attend that Yearly Meeting,
as if a voice had been uttered, "`Go, show thyself to Friends in London.`"
To this she yielded after some mental conflict;
and as the following letter to her husband gives a view of her state of mind,
and of the opening of her concern to visit the continent,
under circumstances that show her dedication to the clear manifestations of duty,
though very much in the cross to her natural inclination,
it may in some measure explain the reasons of her long absence
in this very extensive and interesting religious concern.]

[.embedded-content-document.letter]
--

[.signed-section-context-open]
London, 6th mo.
20th, 1798.

[.salutation]
My Beloved Husband,--

In my last, dated at Liverpool,
I informed thee of my prospect of coming to this
city in order to attend the Yearly Meeting,
from a sense of duty; as it appeared not only consistent with good order,
but also with my blessed Master`'s will,
that I should come and show myself to my friends in a collective capacity,
and give them some account of my last journey;
which I was enabled to do to the satisfaction of Friends and the peace of my own mind.
I may also tell thee, not boastingly, but with a thankful heart,
that I was agreeably disappointed; for I expected to have met with a very cool reception,
and that the language of, What doest thou here?
would have been secretly uttered in the ears of my understanding, if not vocally so.
But through mercy it proved otherwise; for,
instead of being looked down upon with an eye of contempt,
Friends from the different Quarters seemed glad to see me;
and I believe it was so beyond all manner of doubt,
as their conduct both in and out of meeting manifested their unity and sympathy with me;
which was as marrow to my bones.
At one time, several Friends were led to speak to me and my companion Sarah Birkbeck,
in such a wonderful manner,
that I was made to acknowledge on the bended knee of body and mind,
that it was the Lord`'s doing, and marvellous in our eyes.

Thus, I was amply paid for coming to London, and not only rewarded for what was past,
but strengthened and encouraged to give up to an awful prospect
that had opened upon my mind the day we left Liverpool,
of visiting some parts of Germany, particularly those under our name at Pyrmont;
and those in the south of France have also been brought so fresh
in my remembrance that I believed it right when I laid my concern
before the morning meeting of ministers and elders,
to tell Friends that I had but little reason to expect
I should be excused from going there.
This was a great surprise to most, if not all in the meeting,
except a few to whom I had mentioned it a few days before,
in hopes of gaining relief that way,
which gave me peace in believing I had moved rightly in the concern.
But it was trying to my nature to expose myself to
Friends in this city by opening such a prospect,
after having received the third certificate from the Yearly Meeting.
However I had faith given me to believe, that if the concern was right,
way would be made; if not, Friends would be favoured with a sense of it,
and I should be relieved from the painful exercise which I was wading under.
There was considerable weight over the meeting,
and Friends`' minds were dipt into near and feeling sympathy with me,
and there was not one voice lifted against it, but the concurring language was,
Loose her and let her go; and a committee was appointed to draw a certificate.

Ah! my dear, I have no language to set forth the agony of soul I have passed through,
since my mind hath been brought under this unforeseen exercise and prospect.
The day after the date of my last letter to thee,
as we were riding along the road from Liverpool towards Warrington,
my mind being in a sweet composed frame,
I was taking a retrospective view of my long and
arduous journey through this and the adjacent islands,
and did not see where I could mend it, either with respect to time or any thing else,
if I had it all to do over again.
Under this consoling evidence, I said in my heart, I shall go home laden with peace.
This conclusion was scarcely formed, before I heard a voice with my spiritual ear,
saying, If thou dost, thou must go to the continent.
And it has proved as a nail fastened in a sure place,
so that I have not been able to remove it;
and if ever I have felt the terrors of the Lord,
it has been when I was striving to turn away from this prospect.
One night, as I was conflicting with it,
the mournful situation which that humble follower of Christ, Daniel Stanton,
was plunged into after his return from Europe,
for want of giving up to a similar prospect, was brought fresh to my remembrance,
accompanied with a persuasion that if I did not give up,
I should share the same condition;
and instead of coming home with sheaves of enriching peace in my bosom,
I should lose my reward for all I had done,
and become as a withered branch that is to be trodden under foot of men:
and therefore I dared not any longer plead excuses.

Since I have thrown my burden on Friends, I have been favoured with a quiet mind,
and I believe my spirit hath been in some measure borne up above
the floods of affliction by the sympathy of my friends;
and none have felt more deeply for me, I believe,
than dear George and Sarah Dillwyn;--friends in need are friends indeed;
and they have stood by me in the needful time.
George has showed me all the brotherly kindness that my heart could look for:
and therefore my friends at home need not be under any apprehensions
of my moving contrary to the united judgment of the brethren here.

I have now another sacrifice to make,
which is to be separated from my near and dear companion, Sarah Birkbeck;
which is indeed like giving up a right hand, for such she has been to me.
But I see all must be given up, and every prop removed,
so that I must have nothing to lean upon but the breast of the Beloved of souls.
Yet it looks likely that Charity Cook and Mary Swett will supply her place;
they having had similar prospects, even before they left home;
and since I opened my concern, theirs have revived with such weight and clearness,
that I rejoice in the expectation of their company.

With the salutation of love to thee and the children, I remain thy affectionate

[.signed-section-signature]
Sarah Harrison.

--

7th mo.
20th. I can say by blessed experience that the Lord is God, and changeth not;
therefore the sons of Jacob are not consumed.
Although, at times, the enemy may come in like a flood upon us,
yet the spirit of the Lord lifts up a standard against him,
as we are devoted to follow him in the way of his leadings,
saying in the language of him that trod the way to glory before us, Not my will,
but thine be done.
Though this may be a hard lesson to flesh and blood,
yet when the mind is reduced into that state of nothingness
wherein the solemn silence of the flesh is experienced,
hard things are made easy, and bitter things sweet; and then we can say,
Thy kingdom come; thy will be done in earth as it is done in heaven;
and a high-way is cast up where we saw no way;
so that we are convinced that the Lord`'s ways are ways of pleasantness,
and his paths are paths of peace; and as we abide in them,
we feel our peace to flow as a river,
and our righteousness to be as the waves of the sea.

We expect George Stacey and Frederick Smith to accompany us to the continent.

On the 21st of the 7th month, I left London in company with Charity Cook and Mary Swett,
who were also set at liberty to engage in a like concern.
We arrived at Hamburg on the 4th of 8th month;
having been detained a week longer in our floating habitation than was necessary,
by reason of the convoy`'s taking us round by Yarmouth,
and otherwise keeping us in suspense.
While we were on board the vessel we had three religious opportunities;
the last was with the sailors, and I trust it was owned by the divine Master.
We had a meeting appointed for the inhabitants of Hamburg, at which but two men attended;
we also visited a religious family there.--Then set out and reached Hanover,
where we had two meetings on first-day; one in the morning at the meetinghouse,
and another in the afternoon at the inn; which were pretty well attended,
and we were strengthened to relieve our minds.

From Hanover we came to Pyrmont, where we were closely engaged for about ten days;
first in fixing for housekeeping, cooking,
etc. for the people seem to have no idea of entertaining those who come to visit them;
they rather expect to receive than to give:
and indeed there are not more than one or two families that
are in circumstances to do it with any degree of convenience.

We were as comfortably accommodated as could be expected, having three rooms, three beds,
and the use of the kitchen: we found our own provisions, and cooked them ourselves,
with the assistance of a girl and a lad that spoke English pretty well.
Thus we commenced housekeepers at Pyrmont,
in the very house where dear John Pemberton breathed his last.
We went to see his grave,
and I sat down upon it with some serious thoughts that impressed my mind,
fully believing that the Judge of all the earth doeth all things right.

While thus tarrying at Pyrmont, we attended their meetings as they came in course,
and visited the families.
Then went to Minden, which we reached at night; but it being a fortified town,
we were stopped, and obliged to give in our names,--tell whence we came,
and where we were bound, and what our business was.
By this means an alarm was soon spread through the town,--and next morning the magistrates
sent to the Friend at whose house the meeting had been held for seven years,
forbidding him to have any more meetings in his house.
Next day, being the first of the week, meetings were held as usual,
and largely attended by the town`'s people, considering how little notice was given.
On second-day,
the Friend was committed to prison for his disobedience to the command of the magistrates.
Upon this, a messenger was sent to us, forbidding us to hold any more meetings there;
but as it was the preparative meeting day, we thought it right to attend;
which we were favoured to do in the quiet, till just as they were closing the business,
when two officers came with an order from the magistrates
to break up the meeting and seal the door;
but they were civil enough to wait till we had done.
This occasioned a great crowd about the door; and Charity Cook,
feeling her heart warmed with gospel love,
began to call the people to repentance through Lewis Seebohm,
as interpreter.--But the officers came, like roaring lions, and commanded silence;
and taking Lewis by the shoulders drew him away:
so Charity was under the necessity of holding her peace.

We returned to the inn under some discouragement,
not knowing what the consequence might be.
However,
we had not been in long before a summons was sent for Lewis to appear the next day,
at half past two; which he did, and was committed to prison for not taking off his hat.
We were then left in a poor plight;--none of us being
able to speak a word so as to be understood;
and that was not all; for every foot we heard,
we expected they were coming to take us also: which I believe they would have done,
had it not been for that Power that rules and reigns, not only in the hosts of heaven,
but amongst the inhabitants of the earth,
and can turn the hearts of men as a man turns a water-course in his field.
Well, by some means or other their hearts were so softened before night,
that they gave them all liberty to go to their respective homes for the night,
ordering them to appear before them next morning at ten o`'clock.
At the time appointed, they all made their appearance; and, their hats being taken off,
they were admitted into the council-chamber.
After asking them some questions concerning our principles, etc.,
to which they were enabled to give such answers as appeared to satisfy the officers, who,
after giving them a gentle rebuke for their contempt of the court, released them,
and let them go.

I omitted mentioning a precious opportunity which we had
with the counsellor which Sarah Grubb affectionately mentioned,
though she compared him to Nicodemus.
He is father-in-law to Lewis Seebohm.
He had seemed much opposed to Friends; and even while we were there,
he did all in his power to prevent silence; and would have accomplished his desire,
if he had not been requested to be still.
He was then powerfully spoken to,
and was so brought down that it may in truth be said he was humbled as in the dust.
He parted with us in much love and tenderness;
and said he intended to come to Pyrmont to see us again.

After we were liberated from Minden, we came to Rinteln, and had two meetings there.
They were largely attended, and I trust owned by the great Shepherd.
We returned to Pyrmont on the 1st of the 9th month,
and sat with Friends in their morning meeting; also had a large meeting in the afternoon.
Next day the monthly meeting began at three o`'clock in the afternoon.
It was a deeply exercising time, and was adjourned till next day;
when Friends met and proceeded to the business.
We felt much for them; the enemy having got in among them and sowed tares,
which makes hard work for the honest-hearted.
It was thought to be a favoured season,
and our hearts were made glad in believing that they
were under the notice of Him who sleeps not by day,
nor slumbers by night.
There are three particular meetings which compose this monthly meeting; Hanover, Pyrmont,
and Minden.

On fourth-day, we had the company of many of the great folks,
who come here from far for the benefit of the waters.
To them the gospel was preached, I trust, in the demonstration of the Spirit,
by Charity Cook and Mary Swett, and myself had a share in the labour,
to my own peace and satisfaction.

After spending about three weeks with our friends at Pyrmont,
we set out with a view of pursuing our journey to France;
but the wind that bloweth where it listeth, turned us back again.
So we had the opportunity of sitting with them in
their monthly meeting at Pyrmont the second time,
and had good service therein.
In our route we had two meetings at Hameln, also visited the prisoners there,
many of whom are confined for life.
The gospel flowed freely towards them, divers of whom were much broken,
and all took the visit kind.

We went to Hanover the second time,
but were not allowed to hold meetings with the people at large.
However, we sat with those under our name and a few others who came and sat with us,
and a precious, uniting time it was.

On the 13th of the 10th month, 1798, in the evening we reached Friedberg,
and the following day, which was first-day, a meeting was proposed,
and a room being hired for the purpose,
we employed a man to give general notice of the intention.
In about an hour, or somewhat less, after the stated time,
and when perhaps a hundred people were assembled,
the governor of the town made his entry with several soldiers.
Lewis Seebohm being on his feet, he queried of him if he spoke French;
and then by what authority the meeting was held.
On being informed that it was under an apprehension of religious duty,
he made little further remark than that we and all the company were his prisoners.
He then withdrew, though requested to stay, and left the soldiers to guard the room.
Our friends were severally engaged in testimony,
principally in reference to what had occurred, exhorting the people to the fear of God,
which would carry them over the fear of man,
and manifesting in their conduct the stability of their own minds;
which seemed to have an impressive effect on divers,
though the circumstance itself was the cause of much bustle and conversation.
Soon after,
an officer returned with an order for the delivery of the key of our apartments,
and of such papers as we had about us;
and about an hour after this the people were set at liberty.

The meeting began at four, and about nine we were ordered to our apartments,
to which we were conducted by a guard.
On arriving there we found our packages had all been
removed into the women`'s lodging room,
the doors of which were sealed up, and our sitting room only left for our accommodation.
This was trying, to us females especially,
and was rendered more so by having two soldiers stationed
in it as guards--a guard was also placed on the outside,
and the streets paraded through the night by the military.
This conduct bespoke much alarm; but we were preserved calm,
and the night passed without much solicitude or interruption.
Towards noon on the following day, the officers came,
and calling for the keys of our trunks, proceeded to open and search them,
with a view to discover what were our real designs and character.

The magistrates did not appear capable of conceiving how
people should leave their families and engagements in life,
spend so much as we must necessarily do,
and expose themselves to so much difficulty and danger,
on a principle so disinterested as we professed ours to be.
The extent also of our letters of credit, some of them being unlimited,
increased apprehension that under cover of or connected with a religious motive,
there were others less pure, which it became them to explore.
But, conscious of our innocence, we were preserved in a disposition of openness,
and without any mark of fear.

After staying about two hours, they withdrew,
first allowing the women to take out some necessary apparel, and in the evening returned,
but did little more than order the trunks, which had been left on the carriage,
to be taken off and locked up with the rest.

The next night we had three soldiers in the room,
not we supposed from any apprehension that we should be difficult to manage,
but the additional person appeared to be placed as a spy on our actions and conversation:
he was a subaltern officer, who, we had reason fo suppose, could speak English,
and seemed well calculated for the place he had to fill.
With a suspicion of this kind, and to avoid the possibility of misconstruction,
we restrained ourselves from much, even innocent conversation,
and probably disappointed them.
One of our guards had been a priest, and was a sensible man.
We lent them our books, such as the [.book-title]#Apology#, [.book-title]#No Cross No Crown,# [.book-title]#Summary,#
etc. which were read with much attention,
and the quondam priest and another of them yielded to the truths they contained,
and were tender.
The governor also, and other magistrates, had each of them books at their own request,
in order to discover if they contained any thing
which might militate against their political system.
This night was also passed tolerably,
the guards being civil and respectful in withdrawing into the lobby,
on the women`'s wanting to retire to rest, and to rise in the morning;
and during the night, though in the room, they behaved orderly.

The third day came, and no relief.
We understood they had taken down the names of those who attended the meeting,
and had given directions that no one should be permitted to speak to us;
and the officer having required to know what property we had with us,
we were not without suspicion that they meant to take possession of it,
and to attempt the exaction of more on our letters of credit:
but whatever their designs were, they forbore, and therefore it is candid to suppose,
their inquiry was only with a view of more perfectly ascertaining our object and character.
Toward the evening, a messenger came;
and on our complaining of the treatment we received, in so unpleasant a detention,
he observed that the general had been indisposed,
and that more time was wanted for the examination of our books.

We pleaded our innocence of any political object,
and hoped speedily to be informed what they meant to do with us,
and that if they intended to confine us much longer,
it should be where our expenses might be on a smaller scale; and further,
that we considered the honour of the French character implicated in our detention,
as we had obtained their minister`'s visa at Cassel, which was to free us to Francfort.
This messenger promised to represent what we had offered,
but observed that the minister`'s seal was not affixed--we replied,
that they could not dispute its being his handwriting,
which he had himself told us would be sufficient.

Fourth-day morning, our exercise seemed somewhat to abate,
not from any appearance of relief, but from a supporting, renewed persuasion, that,
be the event what it might, we were there in the way of our duty.
About eleven o`'clock, however,
the governor and attendants came to take a description of our persons and ages,
places of birth and residence, and of our occupation;
and then told us we were at liberty to go on to Francfort,
the nearest stage to their territory,
but not to proceed from thence to the French posts beyond,
nor yet to return through that place, on pain of being taken up again,
and actually treated as spies.
To a part of our company this was trying, to others not so,
one of our men having expressed a prospect for weeks before of being released at Francfort.

About two o`'clock we got into the carriage, but before driving off,
the subaltern before mentioned came up in great haste and arrested our departure.
He told us that we were to be escorted to their frontier by the military; and further,
that previous to our being allowed to set off,
he had an order from the general for the expense which we had occasioned them.
Our men friends went directly to the governor to have the matter explained,
and told him that as the subject struck us, it would imply a consciousness of guilt,
which we could not admit; and if it had relation to our religious freedom,
we must submit to further imprisonment rather than
violate our consciences by complying with the payment.
He replied, that was not the ground on which they acted, nor on which it was demanded;
but that they had found us on their territory as subjects of an enemy`'s country,
and had in consequence arrested us;
and this expense had been incurred in guarding us till they
had had opportunity of judging and deciding on our case.
We had before been told,
that on coming into the town we ought to have apprized the governor of our arrival,
and that their suspicions had been increased by the omission
of it--but we were content in not having done it,
because the compliance with this form would probably have prevented
the meeting and the consequent information to the people,
which we have reason to hope our being there had spread among them,
not only by the dispersion of a number of books, but we hope by the example set them,
and the cause of our being among them, attracting notice and inquiry.

The ground being thus clearly stated, we were easy in paying the demand,
which was about a guinea, and thereupon took our leave.
Numbers of the people gathering about us,
testified their satisfaction at our being liberated, and we have some reason to hope,
they will not soon forget or lose the benefit of the visit.
With respect to ourselves, we considered it a providential interference for our release.
Our expressions and actions, as well as papers, having been attended to with jealousy,
had any trace of political design been discovered, or even implied,
we had reason to suppose they would have treated us as spies,
and in a manner that might have endangered our personal safety.

Having been kept in close confinement guarded by
three armed men night and day till the 17th,
we were thus set at liberty to return to England; but not by the way we came:
for we had passed through several towns belonging to them.
They told us if we went into any part of the dominions of France,
we should be taken up as spies, and treated as such;
although they confessed they did not believe we were such.
They treated us with great civility; and I believe several of the guards,
as well as the officers, felt for us, and were truly glad when we were liberated.
We distributed many books amongst them,
and had divers opportunities of explaining our principles to them;
which they allowed to be good.
So that upon the whole, we have no cause to be sorry that we fell into their hands:
for though they have prevented us from paying the debt which
we apprehended due to the inhabitants of that nation,
yet we have the consoling evidence of having done what we could;
and it is cause of thankfulness that our minds have
been preserved in quietness through all.

In a day or two after we were discharged from our prison,
notwithstanding their threats we believed it right to pursue our first prospect,
being under an apprehension that we had too tamely submitted to the commandment of men;
and that we should not be clear without informing our men friends,
that we were willing to make another trial, if either of them would go with us.
But as they entirely declined going with us, we felt ourselves comfortably released;
not doubting the will was taken for the deed.
But we had a great conflict to pass through before a total
surrender of ourselves and our all to the Lord`'s disposal,
was experienced: when this state of resignation was attained, I think I can say,
we would as lieve have gone as not, and I don`'t know but that I would rather,
as we were so near; and I believed they would not have power to hurt us.

In the course of this journey, forty-five public meetings were attended,
besides paying a visit to most of the families of Pyrmont monthly meeting,
and holding several religious conferences.
About six hundred and seventy-five books were also distributed--and
we travelled by land and water nearly sixteen hundred miles.

On the 14th of the 11th month we embarked for England,
and on the 16th landed at Yarmouth, I trust, with thankful hearts.
After resting a few days there, we came in company to Ipswich, where we parted;
Charity Cook and Mary Swett proposing to take the meetings on their way to London,
and myself, after remaining a few days at Ipswich, was taken ill of the cholic,
which confined me for some time at the house of my kind friend, John Head.
The Lord has been merciful unto me, in raising up many sympathizing friends in this land,
who have felt for me and tenderly administered to my comfort and encouragement.
In about five weeks, I was so far recovered as to be taken to Needham,
where I was tenderly nursed by my beloved friend, Mary Alexander.

[.small-break]
'''

+++[+++From Needham, Sarah Harrison wrote home as follows: "`1st mo.
26th, 1799.
If life and health permit,
I expect I shall be at liberty to return in the course of the summer,
but not before the Yearly Meeting; as I am by no means fit to come alone,
and have reason to expect company after that time.
Indeed, without a great change in my state of health,
I shall not be able to undertake such a journey much sooner.`"

No account is found among her papers of the precise
time of her return to her native land,
nor does it appear that she travelled much in the work of the ministry afterwards.
From various causes, she was introduced in many trials and deep provings,
and bodily infirmities so increased upon her as to disqualify
her in great measure for much usefulness in church affairs,
or attending to the concerns of domestic life.
In this state of privation and suffering,
she was an object of the sympathy of her friends;
an evidence of which is furnished in some of the ensuing letters,
selected out of numbers that were sent to her from distant parts.
As she laboured under great difficulty in writing, even in earlier life,
this may account for her omitting to make any record of
probations and trials attendant on her declining years.
The following essay of a letter to a friend (whose name is not
given) was probably one of her last efforts of this kind.
It appears to have been commenced in the 5th month, 1811,
and finished in the month following.
As it portrays her state and condition, even when surrounded with privations,
trials and difficulties,
so it shows that her confidence was reposed in that Arm of power which
sustains the dedicated mind under the changes and vicissitudes of time,
and furnishes the hope of a blessed immortality.]

[.embedded-content-document.letter]
--

[.signed-section-context-open]
Philadelphia, 5th mo.
1811.

[.salutation]
My esteemed friend--

I feel it due to thee to acknowledge
my grateful acceptance of thy kind present,
through which thou hast manifested thy sympathy, and proved the verity of that saying,
"`A friend in need is a friend indeed.`"
I have often thought it would be a satisfaction to thee if thou did but
know how many comforts it afforded me in the course of the last winter,
which was a very trying one to me in many ways.
My state of health was such as required many things which would have been
altogether out of my reach if it had not been for thy kindness;
and I have no doubt it will be gratifying to thee to know how much good it did me.
I trust I may say in truth,
that my mind was often covered with a degree of thankfulness
to Him that opened the heart of Lydia,
for opening thine towards me; for surely it was the Lord`'s doing,
and hath been marvellous in my eyes, that thou shouldst remember thy poor, unworthy,
but sincere friend.
But as it is written, "`They that give to the poor, lend to the Lord;`" so,
we cannot doubt that they will be amply repaid by him who remains to be a good pay-master.

Many have been, and continue to be the trials permitted to assail me, with which,
had not the everlasting Arm been underneath, I must ere this have been overwhelmed: but,
through adorable mercy,
I am at times favoured with an evidence that the foundation of God standeth sure;
and if I am enabled through holy help to stand fast thereon,
I trust all these things will work together for good.

Many are the bodily infirmities which attend me, so that I cannot walk much abroad;
yet through the aid of Friends`' carriages, I frequently get to meetings.
My dear husband is feeble in body and mind,
which has disqualified him for any kind of business;
and this makes our situation the more trying:
however I do not distrust the mercy of Him who hath
promised to bless the provision of Zion,
and to satisfy her poor with bread.
If we are of this description,
I have no doubt the truth of this blessed promise will be
verified in our experience in a two-fold sense.

I observe in the acceptable epistle from your Yearly Meeting to ours,
which was read to the comfort of many,
mention is made of the decease of some of the standard-bearers amongst you:
we have recently experienced a similar stripping.
James Simpson, a valiant in his Master`'s service, was suddenly removed;
and the last month, dear Rebekah Wright was gathered to her mansion of rest.
She was at our late Yearly Meeting, and went home as well as usual.
On fourth-day following, she attended her own meeting,
and that evening was taken with the gout in her stomach, and palsy on the brain,
which in a few days closed the scene.

6th mo.
25th, 1811.
Our well-beloved friend, Hannah Pemberton, has put off mortality;
and we have not the least shadow of doubt that she is now
clothed upon with immortality and eternal life.
She had been rather more poorly than common the greater part of the winter past,
but was not thought dangerous till a short time before she breathed her last,
perhaps not more than an hour: however,
she was gone before any of her friends could get to see her,
which made it rather trying to some of us that loved her.

I wish to be most affectionately remembered to thy beloved wife.
She hath often been the companion of my mind,
more especially since I heard of the trying dispensation which she has had to pass through;
which, no doubt is permitted in unerring wisdom for some good end,
though hid from human eyes.
However, her situation claims the tender sympathy of her friends,
and I think I have felt as much for her as I am capable of.
I feel a liberty to revive a portion of scripture that has
often sprung up fresh in my mind when looking towards her,
and which I think is full fraught with encouragement, in substance on this wise,
"`In all their afflictions he was afflicted with them,
and the angel of his presence saved them, and preserved them from harm.
In his love and in his pity he redeemed them, and carried them all the days of old.`"
Well, my dear afflicted friend,
is there any thing short of his redeeming love that could have weaned
thy affections from the abundance of the good things of this life,
of which thou art in possession, and reconciled thee to sit as in benighted darkness,
without beholding the beauties of this outward creation,
which are so amply displayed;--and have preserved thee in that quiet frame
of mind which from time to time is mercifully afforded thee.

Please to give my love to all those to whom thou may think it will be acceptable:
if I was to begin to name, I should not know where to stop.
In love to thee, thy dear wife and children, I remain thy friend,

[.signed-section-signature]
Sarah Harrison.

--

[.asterism]
'''

For many of the latter years of her life,
she was subject to severe attacks of bilious cholic,
as sometimes noted in the preceding memoirs.
Her last illness was very short, and she expired in much calmness and quietude,
like one going to sleep.

Since most of the foregoing account of the life and travels of Sarah Harrison was printed,
we have been furnished with the following, copied from the record in the family bible,
in the hand writing of Thomas Harrison:

[.embedded-content-document]
--

On first-day, about 4 o`'clock in the afternoon, 12th mo.
29th, 1812, my beloved wife Sarah Harrison departed this life, in her 76th year of age;
and on the 1st day of 1st month was interred in Friends`' burying ground,
at Mulberry street, attended by a large number of Friends.
Having lived with her in great unity forty-eight years and about six months.

[.signed-section-signature]
Thomas Harrison.

--
