== Chapter V

[.chapter-subtitle--blurb]
Letters to Sarah Harrison

+++[+++The following Letter from Joshua Sharples, written while attending Yearly Meeting,
manifests the sympathetic feelings of his mind,
and conveys some encouraging exhortations that may be useful to others.
His testimony concerning his deceased wife Edith, is also worthy of preservation.
It might be well if we had a more minute biographical account of that excellent woman.]

[.signed-section-context-open]
Philadelphia, 27th of 9th mo.
1787.

[.salutation]
Dear friend,--

Thou hast obtained a place in my mind, at times,
with near sympathy and affectionate remembrance,
ever since I first heard of thy concern to visit Friends to the southward;
and about the time of our last Quarterly meeting,
I felt such a lively travail for thy encouragement, support and preservation,
under the prospect, as well as performance,
of thy religious duty,--that I believe I should have then written to thee.
But omission of duty brings weakness, and disqualifies for performing that which,
had it been attended to when prospects were more clear, would have been better.

I fully believe thy trials, both inwardly and outwardly, will at times be discouraging.
The delicacy of thy frame,
and inability (in thy own view) of undergoing the fatigue attending such a journey,
I expect, are often before thee; as well as inward provings, deep baptisms,
discouraging prospects and close trials felt: but He that puts forth,
as there is a confident looking unto him, and relying upon him,
even when faith and hope may be nearly exhausted,
will be experienced to go before and open the way,
to the comfort and encouragement of the weary traveller.
He is a good master; he requires no more of his servants than he gives ability to perform.
I believe, as thy abiding is in him,--casting all thy care upon him,
thou wilt have marvellously to experience his wonders and see his ways in the deep.
Mayst thou put on strength in the Lord, and have confidence in his holy name.
May he be near to keep and preserve,
and enable thee to perform every opening of duty that he may see meet, in his wisdom,
to point out, is the breathing exercise of my mind.

Thou may let Friends know who may inquire concerning my dear wife,
that the nearness which subsisted between her and many dear friends in those parts,
continued while she remained in time;--that it was her joy and delight
to hear from them,--that her travail and concern for their preservation,
was great; and that she embraced every opportunity of inquiring after their welfare.
As she lived,--so she died.
Her zeal and concern for the welfare of society, were increasingly manifest, to her last;
and she was enabled to preach the gospel powerfully in a
public meeting not more than four days before her decease.

Please to remember me affectionately to Thomas Winslow and others of her dear friends,
who may inquire after her; though unknown to me by face,
yet I feel them near for the love she bore for them.
My dear love to Norris Jones and Lydia Hoskins.
In affectionate nearness, I conclude, and remain thy sympathizing friend,

[.signed-section-signature]
Joshua Sharples.

+++[+++Robert Pleasants, the writer of the ensuing letter,
resided at a small settlement of Friends in Virginia.
It may excite the feeling of tenderness in some who are
surrounded with the enjoyments and privileges of society,
very different from those of this Friend, who often went to meeting, and sat alone.]

[.signed-section-context-open]
Curies, in Virginia, 11th mo.
28th, 1789.

It would be one of my greatest temporal comforts to see my children
coming up in a steady attention to the dictates of Truth,
and an honest discharge of duty both to God and man.
I continue in the same lonely situation, as when thou wast here;
and am ready to say at times with the wise man,
"`Woe to him that is alone when he falleth; for he hath not another to help him up.`"
Yea, "`how can one be warm alone?`"--For though I wish not to depend upon man,
I need not tell thee what a comfort and strength it would be,
to have the company and conversation of honest Friends,
engaged for the promotion of Truth in the earth.
And I cant help thinking, at times,
that if the faithful labourers from other places
(where they seem to have enough and to spare,
as in Philadelphia, etc.) were concerned to settle in some remote or distant places,
as I think was the case when Truth first broke forth in the north of England,--they
might come to be numbered amongst "`those who turn many to righteousness.`"
But I know that is not to be expected,
but from clear apprehensions of duty and entire resignation to the Master`'s will.
Nor is such a work to be accomplished in the willings
and runnings of men in their own wisdom and strength,
however great; for, if "`the Lord build not the house,
they labour in vain that build it.`"

I have not, however, been altogether without hope, at times,
that the Father of mercies will not permit the little spark of life, even in this place,
to be wholly extinguished: but rather,
that there may yet be a revival in his appointed time.
But perhaps this may be the effect of desire or imagination, more than any real prospect:
many people however are anxious to hear preaching;
and I believe they are seldom disappointed of hearing
something amongst the methodist and baptist societies,
between whom there appears to be a spirit of emulation who shall make the most proselytes.
I remain thy affectionate friend,

[.signed-section-signature]
Robert Pleasants

+++[+++Sarah Williams, daughter of John Dickinson, was married to Charles Williams,
son of Hezekiah, about the middle of the 3d month, 1788.
She appeared in the ministry when quite young,
and was recommended in the eighteenth year of her age.
She departed this life about the 20th of 7th month, 1789, after a short illness,
leaving an infant daughter.
To those who were acquainted with her, the annexed letter will be an acceptable relic,
and to other young people it may be instructive and edifying.
Sarah Harrison called her an adopted daughter.]

[.letter-heading]
Letter from Sarah Williams to Sarah Harrison

[.signed-section-context-open]
Philadelphia, 19th of 4th month, 1788.

[.salutation]
My dear mother,--

Being kindly informed by thy dear husband of an opportunity
for conveying letters to thee,
I thought I felt a freedom once more to stain some paper,
as a testimony of my unshaken love and sympathy for thee;
and more especially as my mind was peculiarly impressed,
upon receiving such intelligence,
with a sacred and blessed promise uttered by the lip of Truth,
that every one who had left father, mother, houses and children for his sake,
should receive in this life an hundred fold, and in that to come, life everlasting:
the remembrance of which I thought was sufficient
to bear up _such_ through every proving dispensation,
allotted in this state of pilgrimage.
And though `'tis my lot to inhabit, very frequently, the prison-house,
where not so much as one ray of light is suffered to penetrate
the thick walls;--and also to feel strongly fettered,
so that I am not capable of moving hand or foot;--yet have thought, some few times,
that I have been at least suffered to look, as from the top of mount Pisgah,
and to see far into the holy land.
And my spirit has secretly rejoiced in prospect,
that the glorious gospel day which has dawned will rise higher and higher,
breaking down all the walls of opposition which obscure its brightness.--Yea,
my dear mother, permit me to say,
that I believe it has not been for nought that thou hast
been called into that desolate part of the vineyard:
for the Master, it seems to me, is about to visit the highways and hedges,
and to draw as it were the heathen by his powerful love to come in and sup with him.

Oh! how my heart often overflows with love towards those who have
sat in darkness;--believing that light is about to spring up;
and what if it should shine with more distinguished brightness,
where it has been least heretofore known!
Insomuch that it may be said, "`Where is the fury of the oppressor?`"
when the lion comes to lie down with the lamb,
and there is no hurting nor destroying in all the Lord`'s holy mountain.

I wish not to be like the captive exile that hasteneth to be loosed;
yet suffer me to desire thee, if permitted,
still to remember me in thy approaches to the Father of mercies,
that I may in his time hear the language of "`Break the bands from off thy neck,
O captive daughter of Zion.`"
Excuse my disclosure of such sentiments to thee; as it is as I have been wont to do.
Should I be permitted to see thee again, I shall have more to unfold.
Farewell.

[.signed-section-signature]
Sarah Williams

[.letter-heading]
From Lydia Hoskins, Prior to Her Embarking for Europe

[.signed-section-context-open]
Burlington, 3d mo.
9th, 1792.

[.salutation]
Dearly beloved friend,--

I often think of thee,
and have much desired to see thee in this trial of thy faith
and love to thy great and good Master who leaveth not,
nor forsaketh those whose trust is in him, and who are faithfully given up to serve him.
Thou hast known many sore conflicts and deep baptisms of spirit,
both on thy own account and for others,
that the high professors may arise and shake themselves from the dust of the earth,
wherewith many have spotted and defiled their garments,
and by which the best life has been buried in earthly-mindedness:
that so the church militant may more and more arise
and put on her beautiful garments,--may be cleansed,
fitted and prepared to join the church triumphant in heaven.

Ah! my dear friend, these have been and are thy deep exercises:
but the mourners in Zion and the heavy-hearted in Jerusalem
who are travailing for the prosperity of Truth,
shall in due time receive beauty for ashes, the oil of joy for mourning,
and the garment of praise for the spirit of heaviness.
This I believe has been, and will be thy experience;
and He that has been with thee in six troubles will not leave thee in the seventh.
May he be with thee in all dispensations,
whether in heights or in depths--thy stay and thy staff,
and thy safe convoy through time to a blessed eternity.
Yea, may the God of all consolation, grace, mercy, peace, truth and love,
be with thee as a shelter from the storm, a covert from the heat,
and as the shadow of a mighty rock in a weary land.
May he support thee in every trial and close besetment,
and conduct thee safely through all storms and tempests, both within and without;
that so thy labour may be blessed to the churches, to the comfort of the honest-hearted,
and thy own enriching peace and true consolation.

My spirit is clothed with that love and sympathy
toward thee which many waters cannot quench,
nor floods divide; in which I conclude, and remain thy affectionate friend,

[.signed-section-signature]
Lydia Hoskins.

[.letter-heading]
From Jane Snowden

[.signed-section-context-open]
Philadelphia, 1st mo.
26th, 1792.

[.salutation]
Dear Aunt,--

While thinking of my own poverty,
and regretting that I had neither silver nor gold to offer,
I remembered that "`a man was accepted according to what he hath.`"
The remembrance of this scripture passage encouraged
me to make an attempt to write to thee.
Thou mayst be sure, my dear aunt, I was affected, yea, deeply affected,
when I read thy epistles which gave some account of thy tried situation.
Joy, however, soon succeeded sorrow;
because I believed thou wast under the immediate
care of Him who would never leave nor forsake thee.
And though, at times, he may withdraw his presence, and veil himself as in a thick cloud,
there is no cause from this to believe that he will leave thee or forsake thee.
Those whom he loves, he chastens; and the trial of their faith is precious in his sight.
What if he should permit thee to liken thyself to a little one,
and to cover thy head and feel ashamed and confounded because of thy nothingness;--neither
is this any reason that he will leave thee or forsake thee.
He is able to make a little one as a thousand, and a small one, as a great nation.
And he is not only able, but I believe designs to do this for thee,
if thou keeps thy dwelling in him.
Therefore it is necessary thou should be acquainted with thy own nothingness; that so,
when thou hast finished the work given thee to do,
thou may not take any of the praise to thyself;
for verily unto us belongs nothing but blushing and confusion of face.
With sincere desires for thy welfare every way, my spirit affectionately salutes thee,
and bids thee farewell.

[.signed-section-signature]
Jane Snowden.

[.letter-heading]
From Owen Biddle

[.signed-section-context-open]
Philadelphia, 5th mo.
21st, 1793.

[.salutation]
My dear friend and much esteemed sister,--

I feel myself a poor creature,
having often to look back at the hole of the pit from whence I was digged:
and although it affords occasion, at times,
to bless the hand that so marvellously wrought for our escape,
yet it occasions great self-abasement and humiliation.
It is my lot often to be in a state of imprisonment,
and to feel as if bound in fetters and in iron bands;
and Oh! that I may be preserved in these seasons,
in the patient resignation of the creaturely will I believe it
is good for us to have our faith and patience thus exercised,
notwithstanding it is hard to flesh and blood.
But flesh and blood cannot inherit the kingdom; it is that pure,
incorruptible seed which is born from above,
and our being made subject to the will of our heavenly Father,
that prepares us for this inheritance.
May we, my dear friend, so walk in faithful obedience through time,
that we may finally have to rejoice with him through an endless eternity,
in the fruition of his blessed presence in which there is life, and at his right hand,
rivers of pleasures forevermore.

Now, my dear friend, I shall endeavour to give thee some account of other things among us.
Our dear friends, Samuel Smith, Rebecca Jones, Lydia Hoskins,
Grace Buchanan and Robert Smith of Burlington,
have gone to the eastward in expectation of attending
the Yearly Meetings at Long Island and Rhode Island.
Peter Yarnall goes with David Cumming on the same route; but Peter`'s concern, I hear,
is more particularly to visit the island of Nantucket.
Dear Hannah Cathrall is gone to London Grove Quarter, John James attending on her;
Thomas Scattergood is yet on his services in Virginia,
not expecting to return home till after the Yearly Meeting at Blackwater.
Thus, thou mayst see that the servants here are not idle.

Perhaps thou hast heard of the very weighty and exercising service which our dear friends,
Jacob Lindley, John Parrish, Joseph Moore, William Savery,
John Elliott and William Hartshorne have given up to, namely,
to attend an Indian treaty which is to be held many hundred miles from hence,
in the Indian country, at a place called Sandusky.
They have gone with the full concurrence of the people in general,
and particularly of those in power,
who appear much disposed to promote the good work
of pacification in which they are engaged,
as are the officers of the British posts through which they have to pass,
as we are informed.
We have had accounts from William Savery, dated beyond Albany,
on his way to Oswego in order to take shipping on lake Ontario,
thence to pass near the falls of Niagara, and take shipping again on lake Erie,
and proceed to the west end thereof, and to a place called Sandusky,
where it is expected many thousands of the Indians will attend as runners have
been dispatched by them to all the tribes that we have any information of,
some of them living very remote.
At this place it is expected and hoped our Friends
will have a full opportunity with these people;
too many of whom continue in what is called a savage, barbarous state;
although not without a knowledge of that principle which is sufficient to bring salvation.
Many of them manifest the influence of this principle on
their hearts by the most lively expressions of sensibility,
and sometimes acknowledge it vocally.
A circumstance now occurs to my remembrance which is worth mentioning:

Twenty Indians of the Wabash nation left their native country,
about nine hundred miles westward of this, in the beginning of last winter,
to come to Philadelphia in order to ratify a treaty
made with them on behalf of the United States.
On their journey they had to encounter many difficulties,
though treated kindly by the people.
At length they all arrived in this city but one, who died on the way.
The rest mostly came in healthful and stout,
except two who had taken the small-pox on the way.
This alarmed our people in power, as it did the Indians.
The former, being desirous that the Indians might escape the infection in a natural way,
which they considered as being mostly fatal to the Indians,
proposed to them that they should be inoculated.
To this the Indians consented:
but it proved unfavourable--seven of their number
died;--some of them persons of great influence;
and one, a man of a worthy character,
as being noted for promoting a friendly disposition.--Whilst
two of the eldest lay very ill,
our friends, John Pemberton and John Parrish went to see them:
and while sitting by their bedside,
after acknowledging to Friends a sense of their kindness in coming to see them,
and desiring that they would come often to look upon them,--and
that they would consider them as their children,
now they were in a strange land;--one of them addressed the other nearly in these words:
"`Brother,`" said he, "`don`'t be cast down.
We have come upon a good work.
It was the Good Spirit that put it into our hearts to come, to do the good work of peace;
and whether he permits us to return back to our country again, or not, let us be content,
as I believe it will be well with us.`"

This was preaching the gospel, the power of God that brought them to say,
Thy will be done--the highest anthem sung in heaven,
as our dear friend S. F. had to testify.

Since thou left thy dear native place, we have been generally favoured with health.
To the list of interments, which have been few,
may be added that of Richard Mason`'s son Benjamin, who died suddenly last week;
and that of Hannah Kite who deceased yesterday, after a lingering illness,
in which she manifested a desire to be with her dear Redeemer;
and expressed her hope that if she was preserved in patience to the end,
all would be well with her.

On the night after the death of Richard Mason`'s son,
his work-shop (in which were thirteen or fourteen fire-engines,
some nearer finished than others, with all his materials,
and considerable property of his sons) took fire, and was burnt to the ground,
with three or four adjacent buildings.
This loss, in addition to the death of his son,
excited the sympathy of his friends and others;
and large collections were made for the sufferers by which they were in part relieved.

I am, dear friend, with feelings of pure friendship and esteem, thy poor,
unworthy brother,

[.signed-section-signature]
Owen Biddle

[.letter-heading]
Note from John Pemberton

[.signed-section-context-open]
Philadelphia, 5th mo.
13th, 1793.

[.salutation]
Beloved friend,--

I often think of thee, and desire thy support every way,
that thou may be enabled to endure hardness as a good soldier in the Lamb`'s warfare.
Look not back, but press forward.
Discouragements will attend, and many baptisms be experienced;
but this is the portion of all who go forth rightly.
If faith and strength is afforded to discharge the commission,
it is as much as can be expected.
Sometimes the most good is done, when the poor traveller thinks he has made poorly out.
It is a safety to be stripped after seasons of favour: and as the gospel spring is pure,
we need to be often emptied and washed, that it may run pure.
I am a poor, tried creature; but I labour to possess my soul in patience;
and am thy affectionate friend,

[.signed-section-signature]
John Pemberton.

[.letter-heading]
From George Churchman

[.signed-section-context-open]
East Nottingham, 5th mo.
22nd, 1793.

[.salutation]
Dear friend,--

Although I often feel myself as poor as a beggar,
yet a degree of sympathy hath sometimes inclined me to think of thee;
not altogether void of a sense of best fellowship,
nor without a measure of tender desire for thy preservation on the sure foundation.
If we can, through close watchfulness,
be favoured to witness our feet established thereon,
the storms and trials attending our pilgrimage will not be permitted to move us.

Being in company with Elizabeth Coale, of Deer creek,
some conversation occurred respecting some of thy trials in Maryland,
and the singular path which sometimes seemed to tie thy allotment;
of which I also was in measure a witness in Baltimore.
The fresh revival of some of these things increased my sympathy with thee under
thy present engagement in a land more remote from the place of thy nativity,
and added to the freedom I have felt to give thee a little token of my remembrance.
I found, by Elizabeth`'s conversation,
that her spirit was nearly united in sympathetic feeling toward thee,
in thy present gospel embassy.
I take her to be in a lively, improving state;--meekly courageous in the Master`'s cause,
and one who is not willing to turn her back in the day of conflict.
I esteem her as one of the valiants of our day.
She is frequently engaged, of latter time, to stand forth in the gospel line,
with good acceptance; and is on the list of recommended ministers.

I sometimes feel it to be a part of the business allotted me, to endeavour to encourage,
and hold up the hands of honest labourers in the Lord`'s harvest; and,
if I may be worthy, to have a part in comforting the mourners in Zion,
or handing forth a little cheering language to the heavy-hearted in Jerusalem.--When
I am admitted to partake of a degree of Divine favour,
I feel my mind dipped into a lively sympathy with others,
earnestly craving that they with myself may be steadily kept in such a meek,
vigilant state as to receive increasing supplies of that
strength which renders honest labour victorious,
and produces the reward of solid peace.

May wisdom and stability be thy armour and shield; that being thus clothed,
though thou may sometimes have to encounter as with adders, hissing serpents,
or "`beasts of Ephesus,`" thou may feel that preserving power attend thee,
whereby thou canst tread on scorpions, and feel defended from the force of deadly poison.
Therefore take courage,
and let not thy mind be overmuch cast down when deep exercises attend thee.
The Divine arm is not shortened,
neither is the gracious ear of lovingkindness and mercy grown heavy;
for he surely heareth and helpeth his dependant children,
granting them an hiding place as in the hollow of his hand.

[.signed-section-signature]
George Churchman.

[.letter-heading]
From Sarah Newlin

[.signed-section-context-open]
Concord, 6th mo.
2nd, 1793.

[.salutation]
Endeared friend,--

In a degree of that love which neither the foaming billows nor distant lands divide,
do I affectionately salute thee;
with desires that thou may be favoured with free access to the throne of Divine grace,
now in thy arduous undertaking.
Oh! may the Shepherd of Israel be near in every trying dispensation,
and be thy bow and battle-axe; yea, and go before as a mighty Captain,
teaching thy hands to war and thy fingers to fight:
for great and marvellous are his works, just and true are all his ways,
in that he hath hid himself from the wise and prudent of this world,
and revealed his gospel unto babes and sucklings.
Blessed be his adorable name.

When, through exercises and deep wadings, I am at times (with Peter) ready to sink,
I then recollect that it is through many tribulations that we are
to enter the desired port and haven of eternal rest and peace,
when these few fleeting moments come to an end.
And though "`the wicked bend their bow, and make ready their arrows,`"--yet,
in the presence of the Lord there is joy, and at his right hand,
rivers of pleasure forevermore:
though unmixed joy and felicity is by no means a draught for mortal man,
while on this side the grave.

Notwithstanding I expect thou art not wanting for correspondents,
I was most easy to cast in my mite, which, if of no other use,
may let thee know thou art still in remembrance.
Thou art, indeed, at times brought very near to my life,
when favoured to feel love to those who love the
Truth;--a favour that is not at our command,
however desirable.
I often fear that I am "`like the heath in the desert,`"
and scarcely capable of any thing but mourning.
But I wish not unprofitably to echo my complaints:
no doubt it is in unerring wisdom that I am tried; perhaps for my refinement,
and that I may know how frail I am.

It is comfortable to hear that thou art favoured with a suitable companion,
now in a foreign land.
To me it appears as an evidence that kind Providence owns the work;
not only sending his ambassadors over sea and land to invite the people,
but providing them true help-meets to join in his service.

Oh! mayst thou, beloved friend, if consistent with best wisdom,
when done thy Master`'s work,
return once more to thy native land with the reward of that sweet peace
which the world can neither give nor take away,--bringing home,
as it were, stones of memorial, wherein the living in Israel may rejoice.

May He who hath laid the foundation, also lay the top-stone,
finishing his work in thee to his praise who
is everlastingly worthy forever and forevermore.--Amen.

[.signed-section-signature]
Sarah Newlin.

[.letter-heading]
From Elizabeth Foulke

[.signed-section-context-open]
Philadelphia, 11M mo.
29M, 1793.

Though various engagements crowd upon me, after an absence of ten weeks from the city,
I am nevertheless willing to greet my beloved friend with a few lines;
thinking it will be peculiarly grateful to thee to hear from any
of thy friends at the period when this may be likely to reach thee.
I have no doubt that information of the late awful dispensation has, ere this,
spread a painful anxiety over thy mind, and bowed thy spirit in tender sympathy with us;
and thy soul will doubtless melt in gratitude on hearing that the
Lord has not forgotten to be gracious to thy beloved city;
and that his judgments are still mixed with mercy,
as manifested in the recent marvellous display of his power and omnipotence,
at a season when outward circumstances concurred to heighten the virulence of the disease,
and increase its progress.
The coming of rain and cold weather,
towards which the minds of many were too much turned as a source of relief, was withheld,
and the parched earth seemed to mourn with its inhabitants.
At such a time, Almighty Goodness was pleased,
in a manner unfathomable to the most scrutinizing eyes of the learned,
to stay the destroying angel,
and thereby evince that his hand is not shortened that it cannot save,
nor his ear grown heavy that he cannot hear.
Many minds have been brought to acknowledge with reverence that it is the Lord`'s doing,
and marvellous in their eyes.
But I greatly fear lest some of us should too soon be ready to say,
Surely the bitterness of death is past;--and not be enough concerned to bring forth
those fruits of gratitude which may ascend as sweet incense before the throne of grace.

It is impossible for tongue or pen to give a just idea of the awfulness of the scene,
or of our feelings through the course of it.
It seemed, at times, as though the Almighty would utterly desolate the city;
and there being a long remarkable drought which checked and destroyed the vegetation,
so that the face of nature wore a melancholy aspect, seemed to augment the affliction.
But in the midst of all this trouble,
it was painful to see how insensible some were to the message or awful messenger,
whose solemn proclamation of mortality was so constantly saluting our ears.
Yet many others have been secretly clothed with sackcloth and deep mourning.
Previous to this visitation,
I thought the state of things in our society was discouraging;
there seemed to be so few who were willing to put their shoulders to the work.
And now there are so many vacancies, through the removal of so many worthies,
that unless it pleases Him who has thus seen meet to cut short their work,
to raise up others, the burden must fall heavy on the surviving few.

[.signed-section-closing]
I remain thy unfeigned friend,

[.signed-section-signature]
Elizabeth Foulke

[.letter-heading]
From William Savery

[.signed-section-context-open]
Philadelphia, 3d mo.
8th, 1794.

[.salutation]
Dear Sarah,

After long thinking of it,
I now sit down to attempt a few lines as a token of my frequent remembrance of thee:
for I may say, that as far as I have been capable,
I have been united with thee in the endeared fellowship of the gospel;
and the sincere wish of my heart is for thy welfare,
in every sense and in every place where the Lord may lead
thee to be a witness for his name and testimony,
which I know is very dear to thee.
A large and precious portion in the ministry of reconciliation, is bestowed upon thee;
and it is rejoicing to myself and others here to find by accounts from England and Ireland,
that the holy, invisible, but invincible Arm continues to be thy stay and staff,
through weakness of body and many inward and outward conflicts.

The late awful, yet just chastisement of our beloved city,
will no doubt affect thee and our other American
brethren and sisters in a peculiar manner.
You have been witnesses, and some of you partakers,
with other beloved brethren and sisters,
in giving forth warning after warning to a people who have, too many of them,
been ungrateful receivers of the manifold mercies
and blessings of a gracious and long-suffering God.

I did not arrive home from a journey to the Indian
country till the day before our Yearly Meeting;
and was then poorly with a fever, as were several of my companions;
and thou wilt probably have heard that our friend
Joseph Moore deceased soon after our return.
It was then a very mortal time,
and I believe to many a time of awakening to the most important of all considerations.
The Yearly Meeting, though small, was a solemn, uniting season;
and Friends continued together in much resignation.
Thou wilt doubtless receive many minute and affecting accounts of the calamity;
I shall therefore only say, that we feel our loss in religious society to be great,
yet we have this consolation,
that the Lord hath been powerfully at work in the minds of the younger and middle-aged,
to prepare them to show forth his praise.
He hath chosen some, I verily believe, in the furnace of affliction;
and I think there is a lively and animating prospect on the women`'s side of the house,
in a peculiar manner, in the meeting thou belongs to.
May the Lord preserve such as have enlisted under his banner,
and establish them in wisdom and knowledge, to the comfort of his church and people.
Some, I trust, in all the meetings,
have been lastingly profited by the impressions made in the hour of affliction.

But Oh! dear Sarah, how lamentable it is to behold so great a state of forgetfulness,
not only in the city at large,
of those who are hastening into vanity and folly
with as great avidity as ever,--but more especially,
we must mourn on account of that ardour which prevails among many of our fellow professors,
after the riches, splendour, vanities and delusive enjoyments of a perishing world,
which, but so few months ago, were exhibited in their native colours and emptiness;
and also the superior value of an interest in the
favour and protection of Him who mercifully pronounced,
It is enough, and the pestilence was stayed.
Yet the language of this gracious interposition, when every human effort was in vain,
both then was, and now is to me, Go and sin no more, lest a worse thing come upon you.

There is now every probability of our dear John Pemberton and Thomas Scattergood,
joining the little American band in Europe;
and I am confident they will gladden your hearts.
Dear Thomas being a brother especially beloved,
as an honest and dignified fellow-labourer in this part of the city,
I should part with him with deep regret on any inferior occasion.

Our worthy pillar in the church, Isaac Zane, is deceased, and to be interred tomorrow.
He has long appeared to me like one ripe for the kingdom of heaven.
I did think to write by this opportunity to our sister, Elizabeth Drinker,
but whether I shall have time is uncertain.
My dear love to her and all our American Friends.
I have neither room nor leisure to add much to this long letter.
I expect thy very useful Thomas will write by this opportunity.
I may however say, with respect to our sister Rebecca Jones,
so well known to many in England,
she appears to have made a narrow escape from the grave, in mercy to us,
for she continues to be a comfort to many.--With much affection,
I remain thy weak brother,

[.signed-section-signature]
William Savery

[.letter-heading]
From John Pemberton

[.signed-section-context-open]
Pyrmont, in Germany, 9th mo.
21th, 1794.

[.salutation]
Beloved friend, Sarah Harrison,--

It is pleasant and comfortable, when distant friends are enabled to commune in spirit,
and salute each other in the spring of gospel love.
As thou wast oft in my remembrance when in my native land,
so hast thou been in the land I am now traversing, among a people of strange speech,
and in a path of many trials and deep wadings.
Yet the Lord is good, and hath marvellously helped hitherto: blessed be his holy name.

I have been among this people near two months, and yet see no end.
The field is large, and there are seeking people in many parts of Germany,
who are as sheep without a shepherd;
and who want to be directed to the great Shepherd and feeder of his people:
and some of these receive the Word with gladness.
But there is a great mixture,
and it will take time to wean some from long customs and habits.--At
this place there is a number who assemble as Friends do;
and divers of them know the value of solid, awful retirement,
and are seeking to be fed and nourished from the Divine source.
We have been with these, now two weeks, and expect to remain a week longer.
Indeed, I came here in a very poor state of health,--having some weeks before taken cold,
which brought on a chill and fever, and left me weak with a slow inward fever;
but it has not prevented my attending the meetings, of which I have been at six here,
besides divers conferences.
By advice of a physician, I am drinking a saline water,
this place being famous for mineral waters, and I gather strength,
but find I cannot endure as in days past.

My being in this land was much unexpected.
We strove to get landed in the northern islands, but were disappointed: and,
being brought to Holland, I was led deeply to consider wherefore it was thus;
and my mind, after about eighteen days stay at Amsterdam,
was led to look towards Germany, and was enabled to yield to the prospect:
I trust it is in the line of Divine appointment, though a trying path;
but labouring after resignation, things are made easier than I could expect;
and the Lord hath made a way where there appeared to be none.
So that his ways are not only past finding out, but are works of wonder.

This being the day our Yearly Meeting at Philadelphia begins, my mind hath often,
for days past, looked towards our dear Friends there, with desires renewed that wisdom,
counsel and help may be afforded.
The sickness last year occasioned many matters to be referred:
so that the business will be increased.
Many worthies are removed,
and too few deeply enough concerned after a religious growth and improvement.
Fading things too much engross the minds and entangle the
affections of many in our favoured religious society:
and thou knows it is said, we cannot serve two masters.

I make no doubt it was a close trial to thee to hear of the removal of thy dear neighbour,
our valued friend, Elizabeth Drinker.
But she departed gloriously and triumphantly in the field of labour, and, I doubt not,
is safe in her heavenly mansion.
May our close be crowned with the same evidence, whether we end here in Europe,
or in our native land.

It hath been cause of gladness to me, that thou hast been enabled to journey,
and helped to discharge thy burden.
May the Lord, in the riches of his mercy,
be pleased to continue to be wisdom and strength,
that so thou mayest perform the remaining allotted portion of labour; and,
if permitted to return, to return in peace,
with the evidence that thou hast done what thou could.
My dear love to thy dear companion and fellow-helper, Sarah Birkbeck,
also to friends that may know, or inquire after me.
I expect thou knows that Alexander Wilson is with me; he is well,
and labouring to stand approved in the Divine sight;
he joins in near affection and sympathy with thy loving friend,

[.signed-section-signature]
John Pemberton

[.letter-heading]
From James Pemberton

[.signed-section-context-open]
Philadelphia, 12th mo.
14th, 1795.

[.salutation]
Dear friend,--

Think not because of my long silence, that I have been unmindful of thee,
or my love diminished since thy separation from us for the gospel`'s sake; no, certainly;
I may assure thee otherwise,
as thou hast been frequently and almost daily the object of my remembrance and sympathy,
from some sense of the weight of the work in which thou art engaged,
and the path allotted thee to perform it;
wherein thou must have passed through multiplied probations of faith,
and many deep baptisms.
I have gladly heard of the strength of mind and body
with which thou hast been mercifully sustained,
to carry thee through thy religious labours,
so far as thy last account gives intelligence,
which there is no reason to doubt will continue to attend,
until thou art favoured with an evidence of having faithfully accomplished
the services which thy good Master required of thee on that side the ocean,
and a language intelligible to thy spiritual understanding
will be conveyed to that effect.

Such a pleasing prospect may probably be presenting
to thy view about the time this letter reaches thee,
and the nearer it approaches the more pleasant will it appear; but, my dear friend,
embrace it not too earnestly.
Suffer not natural and domestic attachments to have an undue draft.
This will be a time,
in which thou wilt have need of a renewed portion
of light and wisdom to direct thy determination.
Wait patiently; look well around thee; and if any duty more or less extensive,
presents before thee, put it not off too readily.
I mention this as a caution only, in the freedom of brotherly love,
having been a witness of painful consequences in divers instances,
which have ensued to some dedicated servants, in whom fear of detention, diffidence,
and other considerations have united to occasion
their movements homewards to be too hasty,
and on their return a burden has been felt more heavy than they could well bear;
and I wish thy restoration to thy connections and
friends may not be alloyed with any uneasy reflections,
but that thou mayst meet them in full possession of a measure
of that Divine peace which thou hast been labouring after.
Then thou wilt be enabled to look back on the various exercises,
dangers and preservations, that have attended in the course of thy voyage and journeys,
with heartfelt thankfulness to thy holy Leader and Deliverer, who,
though he suffers his servants to be closely tried many ways,
and brings them by a way that they knew not, and in paths they have not known,
yet they are made witnesses of his promise to make darkness become light before them,
and the crooked ways straight, and also that he would never leave nor forsake them.

Thy son John being preparing to embark on a visit to thee,
with a view also of obtaining some further information in the chemical art,
I am unwilling to omit so favourable an opportunity
of giving thee this salutation of my love.
Although I might enlarge on divers matters respecting our situation, it appears needless,
as I expect John will be able to satisfy thy inquires in general,
and being myself imperfectly recovered from a fit of illness
which reduced me to a very weak state of body.
The disease was so extreme upon me for about ten days,
that the physicians and others around me expected
the solemn period of my dissolution was near approaching,
but through adorable mercy I was preserved in a good degree of tranquillity of mind,
labouring after that state of resignation with which my
dear brother was so much favoured during his last illness,
and to his departing moments.
It now seems likely I may be permitted to continue
a little longer in this state of probation and conflicts,
which I wish to be qualified through the renewed
aid of Divine grace to improve to the best advantage,
and my most essential and durable interest,
with gratitude of heart to our most merciful Benefactor.

This is the second attack of illness with which I have been visited since receiving
the affecting account of my beloved brother John Pemberton`'s removal,
wherein I have no doubt we had thy near sympathy and condolence.
As thou wast not a stranger to his virtues, I need not attempt to describe them,
but may justly say, his example,
his integrity and dedication of heart to his prospects of religious duty,
and the qualifications granted him to perform them,
occasion the event to be a general loss,
and particularly to Friends and others in this city, and some of us are sensible thereof.

My wife unites with me in tenders of unfeigned love to thyself
and thy fellow-labourers in the gospel from America,
as thou may have opportunity.
I am thy affectionate friend,

[.signed-section-signature]
James Pemberton.
