== Chapter II

=== Sarah Harrison`'s Account of a Family Visit at Indian Spring, Baltimore, Gunpowder, Etc.

6th month 7th, 1789.
At Baltimore, attended the select meeting yesterday,
and two public meetings today at the courthouse, which were well conducted.
Peter Yarnall and William Savery had good service in them both.
There is to be one at the same place tomorrow morning, and another at the meetinghouse.
At the close of these meetings, the business of the Yearly Meeting will be opened.

14th. Tomorrow I expect to leave Baltimore for Sandy Spring,
to visit such families as I may feel a draft for--whether in membership or not.
I wish to stand resigned to the Lord`'s will in all things.
I know he is able to make hard things easy, and bitter things sweet, and in him I trust.
I have been much shut up since I came to Baltimore, and have had some deep baptisms,
no doubt intended for my refinement.

We accordingly attended the monthly meeting at Sandy Spring,
and I opened my concern to visit the families--which was united with,
and a committee appointed.
On seventh-day, the 20th, in company with John Cowman, Hannah Hopkins,
John Brown and John McKim,
we made a beginning--and visited all those at the Clifts who lay any claim to our principles--had
also three public meetings among them to as much satisfaction as could be expected.
They are indeed like sheep scattered upon the mountains,
having none to watch over them but the Shepherd of Israel.

7th mo.
21th. We have been closely engaged for five weeks in visiting
families within the limits of Indian Spring monthly meeting.
It is a very mountainous country, the roads very bad, and Friends live a great way apart;
so that it took us longer than we expected.
We rode about five hundred miles, and visited seventy families,
besides attending twelve meetings.
Tomorrow we expect to make a beginning here at Baltimore,
with Evan Thomas who has got a minute from his monthly meeting for that purpose.
After various trying seasons, the visit was accomplished,
and in the 8th month we went to Gunpowder;
where our labour was extended to many families who had been disowned,
and marvellous it was to see the openness and tenderness manifest among these.
So that we have been amply rewarded for giving up to visit them.
Commenced visiting families at Baltimore, but the chariot wheels seemed to run heavily.
Felt myself very poor and weak, so as at times to be almost ready to desert the cause,
lest I should bring reproach on the Truth.

Wrote home as follows:

I think much about my dear children, desiring they may be preserved from evil,
and kept out of the streets as much as possible,
for there is nothing of good to be learned there;
and evil communications corrupt good manners.
May you remember, dear children, that you must give account to Him that made you,
for every idle word you speak;
and that there is nothing that works abomination or makes a lie,
that shall ever be able to enter into the kingdom of heaven.
My dear children, I am afraid there is a cause for my writing in this manner.
See to it; for that which is done in secret, shall be brought to light.
The Lord will not acquit the wicked, nor let the guilty go unpunished.
So partake not with them in their sins, lest you also partake with them in their plagues;
but come out from among them, my children; and wash you, make you clean,
put away the evil of your doings; and I will receive you, says the Lord.

Now, my sons, if sinners entice you, consent not; but if you have sinned, do so no more,
and seek to know the God of your father and mother.
If you seek him, he will be found of you,
but if you forsake him he will cast you off forever.
May this, my dear lambs, never be your unhappy lot,
is the fervent desire of your poor mother that is
travelling up and down for the good of others,
leaving you to the care and protection of Him who cared for me,
when I had neither father nor mother to watch over me.
He was pleased to visit my soul when very young with his dayspring from on high;
he preserved me in the hours of strong temptation,
and kept me from falling into the snares of the enemy.
Oh! may living praises be ascribed unto his worthy name by me and mine forever and ever,
says my soul.

I have no greater joy than to see my children walk in the Truth; and O, my dear husband,
may your attention be turned toward them,
looking for strength to enable you to lay hands on wrong things,
both in your own and others,
in the meekness of wisdom--taking the little foxes that hurt the tender vine;
for of a truth, our vine has tender grapes.
Little things in the day of visitation, hurts the tender buddings of Truth in the mind.
The beloved youth feel conviction in their minds,
even when they see that we who are fathers and mothers
appear to have no scruples in ours,
but are inclined to lean toward the fashions and customs of the world,
endeavouring to gratify the lust of the eye in others.
Thus our own children will be taken in the snare,
and we shall not have strength to reprove them for it,
nor to place judgment upon wrong things in them in the authority of Truth.
I feel an uncommon concern for the children,
and wish we may do nothing to weaken our hands;
for I see the time is coming when we shall need strength to say to our offspring,
follow us as we have followed Christ;
and there is no way to obtain it but by being diligent in business, fervent in spirit,
serving the Lord.

After a beginning made in the family visit,
the way closed up so that we could not proceed.
So we attended the monthly meeting, and produced our certificates,
but had no strength to open anything further.
Some Friends were appointed to accompany us--but a dark cloud seemed to hang over us,
and some very close trials came upon us,
through which we laboured as Truth opened the way in a line of plain dealing.

On hearing the sorrowful account of the death of our dear adopted daughter,
Sarah Williams, wife of Charles Williams,
which was the greatest shock I have met with for a long time, the language occurred,
"`Weep not for me, but weep for yourselves and your children.`"
May dear Charles be enabled to refrain his voice from weeping and his eyes from tears.
His loss will be amply made up as he submits in resignation
to the will of Him who knows best what is best for us,
and for the church,
and is able not only to strip her of the ornaments
with which he has been pleased to adorn her,
but also to raise up others to supply their places.
May a double portion of her spirit rest on him and on his dear little girl,
is the fervent desire of my mind.
Dear Sarah has been the subject of my thoughts almost every day for several weeks,
while we have been visiting families; and often in the course of my testimonies,
I have had to mention her zeal for the honour of Truth at so early a period of her life,
though she laboured under many difficulties and discouragements.
Many trying circumstances of her life were brought to my remembrance,
as well as her growth and experience in the work of religion,
and at what age her mouth was first opened in meetings.
She was recommended to the meeting of ministers and
elders at about the age of eighteen years.
And now I believe I hear a voice saying,
write "`Blessed are the dead who die in the Lord;
for they rest from their labours and their works do follow them.`"

8th mo.
21th. I am trying to learn, in whatsoever state I am, therewith to be content;
so that I may come to know both how to be abased, and how to abound,
and that in all things I may be instructed,
and brought to see more and more into the mysteries of godliness, which are great indeed;
and when the Lord is pleased to open them to our understanding,
they are marvellous in our eyes,
and we are made to acknowledge that in him are hid all the treasures of wisdom and knowledge.

24th. Having finished the family visit at Baltimore, under many trials and difficulties,
we left the town and went to Gunpowder in order to
visit the families of that monthly meeting.
I desire to stand resigned to the will of the great Master in this and all other cases,
that so when I have passed this vale of tears,
I may be prepared to leave the world without a fearful apprehension
of hearing the woeful sentence passed on me,
that was on him that had left his talent unimproved.

In this place we have met with some sympathizing
friends that have the cause of Truth at heart,
and the work goes on to much more satisfaction than in time past--the
Shepherd of Israel being felt to be near from family to family,
opening not only a door of utterance,
but also a door of entrance into the hearts of the people.
Some of those visited have been disowned for fifteen or twenty years;
and it is marvellous to see the openness and tenderness among some of these;
so that we feel amply rewarded for having given up to visit them.

+++[+++In the early part of the 9th month, while engaged in the family visit,
her son Thomas was taken with a fever and died.
On this occasion a messenger was sent to inform her of this afflictive event.
A friend present gave this account of her when the information was communicated to her:
"`It was a shock to nature, but in a short time she experienced a calm,
and was enabled to supplicate the Father of mercies in a very affecting manner,
on behalf of her husband and herself,
that they might be preserved in a state of perfect resignation to the Divine will,
so as to say with Job,--'`The Lord gave and the Lord has taken away:
blessed be the name of the Lord.`'`"]

9th mo.
22nd. I have been supported under this close trial that
infinite Wisdom has seen fitting to permit me to pass through,
far beyond my expectation.
Although the next day after hearing the afflicting news,
I found it hard work to keep my mind stayed where it ought to be,
as we went from house to house on the family visit.
The Lord, in the riches of his mercy,
has now given seven of our children their portion among the saints in light,
I trust and believe, so that our care on their accounts is at an end.
I feel as if I would rather see them all taken in a state of innocency,
than for one of them to live and grow up in sin, although I love them dearly,
and do feel the ties of nature to be strong.

On leaving Gunpowder,
I felt great sweetness of spirit till we reached
a friend`'s house near Little Falls meetinghouse.
From there proceeded to visit the families of that meeting,
also attended the monthly meeting at Gunpowder, and returned home with peace of mind.

+++[+++The following Letter was received from Samuel Smith,
written while he was on a religious visit in Europe.]

Spring Mount, Near Cork, 9th mo., 1789.

Dear friend, Sarah Harrison,--

Having taken up a resting quarter for a few days
at our great and kind friend Samuel Neale`'s house,
I mean to employ some of my time in conversing with some of my dear Philadelphia friends;
and although I have not written to you before since my landing in the eastern world,
yet you have often had a place in my near remembrance.

I have now passed about half through this nation,
and enjoyed better health and spirits than has been usual for me,
or than I did any way expect.
I have been trying to get on the King`'s horse;
but find it so difficult to keep the saddle, that sometimes am scarcely mounted,
but down in the ditch, and at the gate again, a poor beggar.
However, I think there is encouragement, if you incline to come over and try your hand.
Two sisters have been here, and lately returned to England;--two more, just arrived;
and two others expected shortly.
So that I suppose the females may understand the matter, and fare better than I do;
and yet I dare not complain.
Wonderful indeed has been the kindness and condescension of the everlasting Shepherd,
in having thus far sustained, kept,
and I hope preserved in the way wherein I ought to go;
insomuch that I feel no sensations of pain or uneasiness at anything left behind.
This I boast not of,
but believe it may be partly through the prayers and intercessions of some of you,
my dear friends left behind, for my safe guidance.
Here also, I meet with some who, I believe, affectionately desire my welfare,
and at times with some of these have had to rejoice,
under a feeling evidence of that hand and arm of Divine strength being underneath,
which is able to carry through and over all.
There are many valuable brethren and sisters in this nation,
with whom I feel a near union, and at times, communion of spirit.
They are worth visiting; and when you find the western wind sets strong this way,
the idea of distance and mountainous difficulty, far exceeds the reality.
A fair wind and the heavenly Pilot`'s direction will soon waft safe and well over.

And now, dear Sarah, I hope you will continue to remember me,
and also to visit my better half left behind.
I know, indeed, she will fall under the tender notice and sympathy of many of you;
which I hope will help to keep up her head above the discourager.
My dear love to your sister and niece.
I greatly desire her improvement, through faithfulness in occupying the gift which,
I have no doubt, has been dispensed,
and not intended to be smothered in the lap of diffidence or false fear.
With dear love to yourself and husband, and any other in your freedom,
I remain your sincere friend,

Samuel Smith.

+++[+++To which Sarah Harrison wrote the following reply:]

Dear friend, Samuel Smith,--

My will is good enough to write you a long letter,
but my stock is so small that I know not how to come at anything worth your perusal.
If I speak of myself what shall I say, but that I remain much as usual,
in the land of doubting and fear.
I was going to say, I love the brethren.
How true that is, I must leave: but I desire not only to love them, but the Master also;
and to follow him wherever he leads, let it be east, west, north or south.
But you know that I am very illiterate, and a person of not much observation;
therefore I cannot so easily discover which quarter those piercing blasts came from,
as some of you learned men can,
that are better acquainted with the points of the compass than I am.
Therefore,
it is necessary for me to wait in the patience for the arising
of that Power that causes the wind to blow when and where he wishes.
But though we know that we hear the sound thereof,
yet know not from where it comes nor where it goes,
till he is pleased to open our ear to hear, as the learned;
even as those that have learned in the school of Christ,
to know his voice from the voice of the stranger.

If I am favoured to hold out till I come to this knowledge,
and find the wind set strong any way, I believe, for peace sake,
I shall go and try my hand.
Although I well know that I am a very poor hand, yet I have this consolation,
that where there is little given, there is little required.

I have been very poorly the greater part of this winter, and am confined to my chamber;
but may say I have passed through some of the closest conflicts since I saw you,
that I ever met with.
No doubt you have heard of the death of our dear son, Tommy,
which happened while I was in Maryland.
And although I was favoured to bear it with becoming patience at the time I heard of it,
yet when I came home, that with other inward and outward trials,
had like to have shaken me off the foundation;
but at present I feel much better settled in calmness.
May the praise be ascribed to Him to whom it belongs, now and forever.

[.asterism]
'''

On the 8th of 11th month, 1790, I joined our beloved friends,
Mary Ridgway and Jane Watson, in their religious visit to some parts of Maryland;
and I may with thankfulness say, they have sealed my former testimonies in that land.
We travelled in near unity of spirit, being made one another`'s helps in the Lord,
so that it seemed hard to part.
But on leaving Maryland, and feeling myself clear of further service there,
I looked toward home, with full expectation of returning;
but He that has a right to all our services, ordered it otherwise.
We came on together to Wilmington, and soon after we reached that place,
a visit to the families of Friends there, presented to their minds,
and I saw a door opened for me to release myself of a burden I have felt for many months;
so I joined them in the service,
which took us till some time in the 12th month following.
We have had many baptizing times together,
especially under the ministry of these dear women, who have been wonderfully favoured,
and had even to bring to light the hidden things of Esau, to the admiration of many.

+++[+++The following extract of a letter to Sarah Harrison, from Jane Watson of Ireland,
now about closing a visit to this land,
and expecting to embark with Sarsh Harrison for Europe,
has reference to some of the trials attendant on such religious concerns,
and manifests the unity and sympathy of the writer.]

4th of 5th month, 1792.

The restoration of your health,
we look upon as a singular favour from Him who can wound and heal as he sees fit.
Your trying prospect may operate on the body in many ways,
as it is so nearly connected with the mind; but if the bitter goes before the sweet,
it makes the sweet the sweeter;
and I hope the bitterness of death is past for the present,
until the time comes when there will be a saying
_farewell_ to the nearest connections in life.
To us, it will be a saying farewell forever to many of our beloved friends in this land,
that are near and dear to us.
I almost dread the time: but so it is; here we meet, and here we must part,
in this world of uncertainties.
But may we be favoured to meet in that world that is certain, and that never has an end,
where all sorrows will cease, is my fervent desire.

Oh! what hurries and commotions there are in the present world and all about it!
It sometimes looks as if the minds of some were always on the rack,--contriving
and scheming one day what they are to do the next,
as if they were always to stay here.
And when they are seized with sickness,
how they have to look over a life of hurry and bustle,
and see that they have not endeavoured to seek quietude,
and therein experience that strength which would make hard things easy,
and sweeten the bitter cups of affliction and trials.
Is there not, with many, a seeking after great things, though the Divine command is,
seek them not; and by that means the greatest thing, the one thing needful,
is too much neglected.
If this were earnestly sought after, it would bring all things into regular order,
and the mind would be satisfied with few things,
so that the blessing of heaven was on them.

I hope you will not be discouraged or impatient:
for you may be assured we will not make any unnecessary delay.

Jane Watson.
