== Chapter III

[.chapter-subtitle--blurb]
Journey to Europe

I left Philadelphia the 15th of 7th month, 1792,
and landed at Liverpool the 16th of 8th month.
Sailed from there, and landed at Dublin in Ireland, in company with Sarah Benson,
wife of Robert.
Attended about thirty meetings, and travelled about six hundred miles,
till we came to Cork.

We left Cork the 20th of 3rd month, 1793,
and rode upwards of forty miles to William Fennel`'s, at Garryroan;
went to their meeting next day, at which was a marriage,
and a large collection of people.
I was renewedly made sensible of my own nothingness; but best help was witnessed,
and the water made wine; so that, I trust, the cause did not suffer that day.
We lodged at Joseph Jackson`'s, uncle to William.
Next day, went to Clonmel, where we spent a week,--were at their first-day, week-day,
and select monthly meeting, and I was led in a line of close labour in them all.
From there, we proceeded to Waterford, and were at four meetings there,
in all which I was silent.

On fourth-day, set out for Mountmellick Quarterly meeting;
where a large share of the wormwood and the gall fell to my lot.
Then taking meetings on the way, we reached Rathangan, where Jane Watson lives;
spent the evening with her, part of the time in her little room up two pair of stairs,
where she has everything neat, though is not much of her time at home.
On first-day following I went to meeting,
or at least to the place where the people were gathered;
but I was not favoured to meet with Him whom my soul loves,
and thought I might adopt the expressions, "`They have taken away my lord,
and I know not where they have laid him.`"

After attending the Half-year meeting in Dublin, we sailed for Liverpool,
and had a favourable and speedy passage of twenty-two hours.
Here I parted with my dear friend, Sarah Benson,
with mutual tenderness of affection and unity of spirit.
From here I proceeded toward London, in company with Hannah Gaylard,
a young woman from Liverpool;--took some meetings on the way,
and attended the Yearly Meeting.
Friends are very kind to me, and their hearts are open to receive me into their houses;
but whether they will receive my testimony in this place, I know not:
for indeed I am not a polished shaft; and they are a wise people.
This Yearly Meeting was large,
and favoured with the overshadowing of that love which is both ancient and new;
under the fresh influences whereof, the business was conducted in love and harmony.
Dear Elizabeth Tuke attended; she is a mother in Israel, and was truly affectionate to me.

In company with Elizabeth Wigham, I left London the 21st of 6th month,
and proceeded by way of Reading, Bath, and Bristol to Wales; where,
as well as in England, we found the life of true religion to be mournfully low.
We attended the Quarterly meeting at Pontipool in South Wales,
where the whole number of men and women amounted to twelve.--Friends in
these parts are so few that their meetings must either be discontinued,
or held in this way.
We have been at several meetings where there were
but two or three members belonging to them.
There remain about a dozen small meetings in Wales.
We returned by way of Shrewsbury, Colebrookdale, and Warrington to Liverpool,
having several meetings on the way.

Having Hannah Gaylard for companion, I left Liverpool the 27th of 8th month,
and went by way of Kendal to Carlisle and Moorhouse, where my brother-in-law,
John Harrison, lives; and he agreed to accompany us through Scotland.
In this country, we travelled about five hundred miles, and had twenty meetings;
several of them were among professors of other societies.
The people behaved well; and I believe there are many seeking souls among them,
that are weary of a hireling ministry.

We arrived at Newcastle, the 13th of 10th month, on our return from Scotland;
and from there continued our travels and daily attending meetings
till we reached White-haven on the 9th of 11th month.
We often hear alarming accounts of the yellow fever`'s
raging in Philadelphia to a very great degree.
But I endeavour to keep my mind as quiet as I can;
and to put my trust in the great Preserver of men,
who is able to do all for my absent and distant friends, that I can desire for them.
I trust I feel as the affectionate wife and tender
mother toward my dear family left at home;
but desire to gather instruction from the apostolic exhortation; to be careful,
or over-anxious about nothing; but by prayer and supplication, with thanksgiving,
let my request be made known unto God.
This is what I labour for, that so I may be supported through every trying dispensation,
which infinite wisdom may permit me to pass through.

11th mo.
30th, 1793.
More moving accounts of the situation of that once highly favoured city of Philadelphia.
Surely the Lord is about to stain the pride of all human glory,
and to bring into contempt the honorable of the earth.
I have long looked for something of this kind to come upon that joyous city,
whose inhabitants had grown careless; they eat and drank, and rose up to play; and,
contrary to the will of God and the counsel of their best friends,
they erected a house for that purpose, which I hope will be put to a better use:
for it is written, "`When the judgments of the Lord are in the earth,
the inhabitants of the world will learn righteousness.`"
May the awful scene that has been before the eyes of the remnant that is left,
produce this blessed effect, is the desire of my soul.

1st mo.
23rd, 1794.
I am truly glad to hear that the dreadful calamity in Philadelphia has stopped;
and that many of my beloved friends and relatives in that once highly favoured city,
found a hiding place while the awful scourge passed over.
May it be solemnly and instructively remembered by the remnant that are left;
and particularly by those who were on the spot,
and beheld the distresses of their fellow creatures, as with terror and amazement.
May it prove a lesson of deep instruction,
not to set their hearts upon these lower enjoyments,
but excite them to endeavour to secure for themselves a house not made with hands,
eternal in the heavens.

3rd mo.
20th. In my travels and labours in this land,
I have been frequently led in a very close searching line;
which is not most pleasant to the hearers,
for the day is come in which the people cannot well bear sound doctrine:
yet they have often been made to acknowledge to the truth of what I have had to deliver,
and some hidden things have been brought to light.
I write this under a thankful sense of the Lord`'s goodness to me,
in that he has been with me, and has often made way for me,
when there has seemed to be no way;--he has greatly enlarged my borders,
and supplied me with fresh matter from day to day, to my own admiration;
so that I get along to the solid peace of my own mind.

4th mo.
24th. There are great commotions in this land.
The people are exceedingly dissatisfied,
and it is said many thousands are going over to America,
which they call the land of liberty: at which I do not marvel,
for times are very hard here.
Many industrious, honest people are already reduced to a state of great poverty;
and hundreds have been compelled to enlist as soldiers,
in order to get bread for themselves to subsist on.
Many also encourage their children to do the same;
and I have seen great numbers with cockades in their hats,
who did not appear to be above ten, twelve, and fourteen years of age,
and so on of all ages till too old for service.
Indeed the whole nation seems to be in a ferment.
Many thousands have been subscribed lately,
in order to hire men to supply the place of the militia,
so that they may be at liberty to go at a minute`'s warning to any part of the country,
if occasion should require it; as well as to assist in guarding the cities against riots.
The clouds indeed seem big with tempest, and if they burst,
the earth with the inhabitants of it will be terribly shaken.
Oh! that we, as a people, may be concerned to dig deep,
and to lay our foundations upon that eternal Rock,
against which the gates of hell can never prevail.

I arrived at London the week before the Yearly Meeting,
and hearing that my dear friend Elizabeth Drinker, was ill at Staines,
about twenty miles distant, I went immediately to see her, in company with Martha Routh.
She appeared to be resigned; but said she had passed through a great conflict,
before she could say, Your will be done.

7th mo.
28th. We have had near forty meetings, since leaving London;
many of them where no Friends lived.
They were mostly large and held to good satisfaction;
in one of them a considerable number of priests were present,
and my testimony was very close against all dead formality.
At first they appeared uneasy, but became more quiet and attentive,
and the meeting ended well.
Next day had a silent meeting with Friends, which was refreshing to my weary spirit.

8th mo.
4th. Sailed for the Isle of Wight, and landed at Cowes in about four hours;
had a large meeting with the inhabitants in the evening, and next day went to Newport,
where we had several crowded meetings.
Only one member of our society resides on this island.

12th. Received the afflicting intelligence of the death of our dear friend,
Elizabeth Drinker.
A few days after, we went on board the packet for Guernsey,
where we arrived in safety on the 16th. The approach to this island is difficult,
from the abundance of rocks, which, in a storm and rough sea,
must present an awful and tremendous sight.--Many of them project
so much into the water as to be covered when the tides flow,
and then there is great danger; but we had an opportunity of viewing them at low water,
and in a perfect calm; and wonderful indeed they appeared to us.
We took up our quarters at Nicholas Naftel`'s, who, with his wife Mary,
we had seen in London; and they received us very kindly.
The face of a Friend, save the few residing here, about ten in number,
is seldom seen among them--the distance by water being about seventy miles.

We sat with Friends in both their meetings on first-day,
and had several meetings on the island as well as religious opportunities with families.
The next first-day afternoon, the people flocked in to the afternoon meeting,
without any invitation, till the house was full,
which gave an opportunity in some measure to relieve my mind,
and encouraged me to request that general notice might be given for a meeting next day.
As Friends`' meetinghouse was small,
it was thought necessary to look out for a larger house;
and being informed that the chief man of the island had one that was very suitable,
application was made for it.
But he refused to grant it, saying he was sorry for it, but could not help it;
alleging that it would never do, "`for`" said he,
"`though I have a value for the Quakers, and believe they are a very good people,
yet they will not fight;
and if a hundred of the militia should be convinced of their principles,
who would there be to protect the island?`"
So the meeting was held in Friends`' meetinghouse, which was well filled,
and the people generally behaved well; but their expectations were so much outward,
that it seemed hard to get into stillness.
However, light sprang up, and the opportunity ended to satisfaction.

We had a rough but speedy passage back to Weymouth, not without some apparent danger;
but through the merciful kindness of a gracious Providence we landed safely, and I trust,
were truly thankful for his preservation.
We then proceeded toward Cornwall, the Land`'s End,
and so to Bristol and the midland counties.

While at Redruth in Cornwall, sitting with the few Friends in their week-day meeting,
I was led into a feeling sympathy with them in the trial they have
met with in the removal of their late beloved and valuable friend,
Catharine Phillips.
Her loss will be much felt,
not only in this small meeting but in other parts of this country.

My health has been better of late than for many years past,
which I number among the many favours and blessings
conferred on me by the bountiful Giver;
and desire above all things to walk worthy of the continuation of his providential care,
by being more and more devoted to his Divine will,
and endeavouring to do all that my hands find to do:
and yet at the same time I find it as needful as ever I did, if not more so,
to take care not to run before I am sent;
especially as my lot is so much turned toward people of other societies,
which has been the line of labour that I have been led in for some months past,
and increasingly so since we came into Cornwall.--There appears to be great openness,
in many places, among these, and the feet of the messengers are much turned to them.
As to myself, it seems as if I can do nothing among our own people, my way is so shut up;
so that among Friends where one meeting might have been enough,
if the neighbours had been invited,
we have been obliged to have another on their account.

1st mo.
10th, 1795.
We have had one hundred and twenty meetings since
the Yearly Meeting in the 6th month last,
besides what we have had among Friends,
and have taken nearly all Friends`' meetings on the way.
But I have felt my mind more drawn to the highways and hedges, as they may be termed,
than among our own sort.
It has sometimes felt unpleasant to me to be so shut up among Friends,
and quite the reverse among others;
because I am very sensible that some Friends do not like it.

3rd mo.
16th. My health, through mercy, is still preserved in a wonderful manner,
considering the severity of the weather.
I have seldom known it colder in my native land,
and we have travelled constantly during the time of the hard frost,
which lasted about two months, without ever taking cold so as to lay by.

When in Bristol, I was not much engaged in public labour;
for there does not appear to be much room in the public mind to receive the gospel message;
they are so full, some of one thing, and some of another.
The cares of this world, and the deceitfulness of riches,
have choked the word in many minds,
and blinded the eyes of them that believe not in the necessity
of seeking first the kingdom of God and his righteousness.
Yet I humbly trust there are a few names, even in our Sardis,
that have kept their garments from the spots and pollutions of this world;
and these are they that shall inherit the promises,
and be permitted to walk with him in white; for they are worthy,
not only of his protecting care while here,
but also to receive the welcome invitation,--Come you blessed, inherit the kingdom.

6th mo.
4th. I have been enabled to attend all the sittings of the Yearly Meeting in London,
which has been large, and I trust owned at seasons by the Master of our assemblies;
which is cause of thankfulness:
for I think I was never more fully convinced that of ourselves
we can do nothing for the honour of the good cause,
however perfect we may be in the letter of the law: for the letter kills,
but the spirit gives life.
Oh! that the people were more concerned to wait for the
putting forth of that Word which is both spirit and life.
It has always been my lot to wade under great depression of mind in this city;
and indeed it has been very much the case all through the nation,
when I have been among Friends.--But I desire to be content with my wages;
and humbly beg for patience and resignation to my allotment; that so,
in holy submission to the Divine will,
I may be enabled to take the cup from his holy hand, and in all things give thanks.
For, notwithstanding I have had to drink of the very dregs of the cup of trembling,
and of deep silent suffering at times,
yet I cannot call in question the rectitude of my coming to this land,
nor of any of my movements since;
except it be in letting in too much discouragement sometimes.

8th mo.
8th. We are poor, short-sighted creatures, and can see but a little way before us;
and I am well assured that it is right, and in unerring wisdom that this is the case:
for, if we were to see all at once, we should often be ready to sink under the prospect;
therefore it is wisely ordered otherwise.
Herein is fulfilled that declaration of our blessed Master,
"`I have many things to say unto you, but you cannot bear them now.`"
Thus, one thing after another is opened to our understanding,
and we are shown what is required of us, as we are able to do it.
I am above all things desirous to be found faithful in the discharge of my duty,
as the Lord may be pleased from time to time to unfold his will to me; for, in so doing,
I have obtained peace to my mind.

Although, at seasons, large portions of suffering have been administered to me,
yet nevertheless, I have had cause through all to bless and magnify that Arm of power,
which has evidently been underneath, and supported me,
and by which I have been mercifully helped along in my labours and travels.
May the praise be given to whom it belongs.

In this land, there is and has been an alarming scarcity of bread,
so that things wear a gloomy aspect.
The people have been very riotous, and outrages have been committed in many places.
Now though we are not to do evil that good may come of it,
yet I believe the alarm has produced this good effect upon those in easy circumstances,
that they have contributed largely for the relief of the poor,
and to lower the price of bread; which was highly necessary;
for a labouring man could not earn enough to find his family in bread,
and the poor have little else to live upon.
Wheat has been a guinea a bushel!

We lately visited the prisoners in Warwick jail; first,
those who were under sentence of death and banishment, about thirty-five in number;
five of whom were under sentence of death;
and among them a poor woman that was charged with
being one of the ringleaders of the rioters;
of which she declared herself clear.
But, whether guilty or not, we felt deeply for her, and a humbling time it was,
in which we felt the love of the gospel to flow towards
them so freely that I have no doubt they might be saved,
if they would accept of the terms which were freely declared to them.
Two days after, we paid them another visit,
in which we had an opportunity with all that were confined there, together;
and a solemn time it was;
such a one as I never saw before;--the floor was sprinkled with their tears.
May they profit by it, is my sincere desire.

In the 9th mo., 1795, we visited the Isle of Man, in company with Richard Reynolds,
Robert Benson, Isaac Hadwin, Ann Crowley and Priscilla Gurney.

On the 8th of the month, we went on board the packet about eight o`'clock in the morning,
and set sail with a fair wind which lasted about two hours.
It then changed and set quite against us,
so that our captain thought better to cast anchor in a safe
harbour than to be combating the waves till the wind changed,
which was not expected till the next morning, and so it proved.
He therefore put in at a place called High Lake, where the vessel lay all night.
Many of the passengers, including all our company, went on shore.
We walked about half a mile to an inn,
where our men friends used endeavours to get a bed for me; but all to no purpose,
they were so full of company--yet seemed kindly disposed.
I was therefore obliged to go on with our men friends
to a farm-house about a mile from the inn,
but no carriage could be got for love nor money, and I was exceedingly fatigued.
By this time it was quite dark: so we set off wading along through the sand,
which in some places was very deep: and when we got about half way,
we met one of our men friends who had gone on before and hired a cart.
We all got in and went to the farm-house,
where we met with what we should call good accommodations
in our wilderness country in America;
but some of our company thought it poor enough.
Next morning we returned to our floating habitation, and again set sail;
and in about thirty hours arrived safe at Douglass, on the Isle of Man: for which favour,
I trust our hearts were made thankful,
for if we had had a rough passage I know not what we should have done,
the vessel being small, and I suppose not less than sixty passengers.

Next day, being seventh of the week,
our men were employed in getting a place to hold meetings in, and giving notice.
First-day, we had large and I may say solid meetings; the people behaved well,
and treated us with great respect, and we were visited by the heads of the town.
The governor, who resides about twelve miles from Douglass,
heard of us and sent his carriage to bring us to Castle Rushen,
the place of his residence.
On second-day,
Robert Benson and Isaac Hadwin went there to get
things in readiness for a meeting the next day;
it being thought best for us to stay at Douglass till morning, which we did:
but I was taken so ill that they were obliged to leave me and Sarah Benson behind;
and the meeting had to be put off till the day following.
In the afternoon I was so much better, that I thought I would do what I could; and,
sending for the carriage, we set out,
accompanied by a friendly man of the town who had paid great attention to us.
I bore the journey better than I expected; and having a good night`'s rest,
on fourth-day we had a large and good meeting at Castle Rushen,
the governor and his family attending it.
At the close, he addressed me in a friendly manner,
expressing his satisfaction and unity with what had been communicated,
and gave us a kind invitation to his house.

In the evening, we had a meeting at a village two miles off,
where I think it might be said, the gospel was preached to the poor.
On fifth-day, we had a meeting at Peal-town, which was held out of doors,
there being a large gathering of people, and through Divine assistance,
the testimony of Truth was exalted among them.
On sixth-day we went to Ramsey, and had a large meeting at a school-house next day,
which ended well.
On first-day, had two meetings at Ramsey, the last exceedingly crowded,
so that the people were not so still as could have been desired,
but upon the whole behaved as well as could be expected,
considering they were strangers to our way of worshipping
God in the inner temple of the heart.
There are many up and down, who are desirous of becoming acquainted with this worship;
and I do believe there is a seeking people on this island;
and to these we have been the messengers of glad tidings.
On second-day, we had a meeting at a place called Bern, about two miles from Ramsey,
where many sober people attended,
to whom the gospel was preached in the ability received.
From there we went again to Douglass, and being weary rested on third-day.
The next day, had a farewell meeting with the inhabitants of the town,
and prepared for leaving the island, which we did on sixth-day,
and landed at Whitehaven in the eyening.

The following letter from the governor of the Isle of Man, to Richard Reynolds,
written about the time we left the island, is thought worthy of preservation,
as it has reference to this visit.

[.embedded-content-document.letter]
--

[.signed-section-context-open]
Castle Rushen, 22nd Sept.
1795.

[.salutation]
Dear sir,--

I was yesterday favoured with your obliging letter of the 19th of this month,
and I am only sorry you should have thought any thanks necessary,
for any little civility I had been able to show you and the rest of your worthy company.

It was indeed but very little I had in my power, but I can with truth say for myself,
that my _will_ was good.
Accept, sir, for yourself and friends,
my best thanks for your good wishes for me and my family; and further, in return,
be assured that _mine_ are most sincere, that you all and each of you may,
with the blessing of God,
have a safe and speedy voyage and pleasant journey to your several homes,
and there a happy meeting with your friends,
with all who love you and whom you love;--very especially, and with best respects,
I beg to be remembered to the good elderly lady who has come so
far with the sole view and purpose of doing good to others.
She must, even in this world,
have her reward in that heart-pleasing consciousness
of having discharged what she felt a sacred duty;
and in that world where the intentions of the heart are clearly viewed and justly estimated,
she will be most certain of it.

Be so good as to tell my worthy friend, Mr. Clegg, when you see him, that you were not,
either you or Mr. Benson,
half so willing to receive as I to offer such little civility as was in my power,
(that is,
distinct from that public attention which I conceived and felt my duty,) and
which I shall be ever happy to show to any friend of his;--that I thank him,
however, and most sincerely, for the favour he did me in bringing me to the acquaintance,
little and short as it was, of such worthy persons; which has left me nothing to regret,
but that there was not time for improving an acquaintance which I am very sure would,
to me, have been most pleasing.

_Adieu,_
dear sir--and that the good God and Father of us all who faithfully endeavour to love,
and fear, and serve him, may be ever the guardian and conductor of you and your friends,
is most sincerely the prayer of your and their well-wisher and friend,

[.signed-section-signature]
Alexander Shaw.

--

25th of 9th month, Robert Benson, Isaac Hadwin and Ann Crowly left us,
and we stayed over first-day at Whitehaven.
Sat with Friends in their morning meeting, and had a large public meeting in the evening,
which tended greatly to the relief of my own mind.
Richard Reynolds and Priscilla Gurney left us after the forenoon meeting;
so that Sarah Birkbeck and myself were left alone as to outward help;
but our never failing Helper did not leave us.
It was very trying to part with those dear friends,
after being so long together and so nearly united in gospel fellowship.
On second-day, we had a large meeting in a village by the sea-side, called Benton,
where there had never been a Friends`' meeting before,
except one that dear John Pemberton had when he was in these parts.
It was a time wherein the weak were strengthened and the unruly warned.
From there to Kendal, where we met with David Sands,
who was like a cloud filled with rain,
and he was wonderfully favoured in the Quarterly meeting held here:
but I was as common with me when among Friends, that is, shut up as in utter darkness,
both in meetings and in families.
It is trying; but may I be endued with patience, is the prayer of my heart.

1st mo.
26th, 1796.
Am now at Newcastle-upon-Tyne,
and with thankfulness may acknowledge that I am still able to travel from place to place,
though not without difficulties; for many infirmities attend my tottering frame.
But it is a favour that I am so well as I am;
for we seldom have less than eight meetings in a week, and often more,
beside riding many miles.
I believe we have not rested more than a week, all put together,
since Yearly Meeting in London.
On looking towards the remaining field of labour in this land, I am ready to exclaim,
Oh! that it were possible to finish it by the time of the next Yearly Meeting;
but that must be left.

When I last met with Nicholas Waln at York, he was in a very tried state,
not having opened his mouth in testimony since he left Ireland, nor for some time before.
Poor man! he has to travail in the deeps: and I wish with all my heart,
that it was the case with some others: then, I believe,
the _grace_ would be more magnified, and the _creature_ less gratified,
both in visitors and visited.
And Oh! that I may rightly mind my own proper business.

[.small-break]
'''

+++[+++During the winter, her son John arrived in Dublin,
on his way to attend chemical lectures in London,
for improvement in his business as a druggist, etc.--They met about the 1st of 3rd month,
after an absence of near four years, and it was to them both an affecting meeting.
The allusion to her son in the following extract of a letter to her husband,
relates to his acquiring a further practical knowledge of chemistry, etc.]

[.embedded-content-document.letter]
--

[.signed-section-context-open]
London, 6th mo.
2nd, 1796.

[.salutation]
My Dearly Beloved,--

In the remembrance of that saying of the holy apostle, I take up my pen to salute you,
namely,--"`We know that all things work together for good to them that love God.`"
And as I humbly trust we are of the number of those that
are afraid to disobey any of his righteous commands,
I hope the disappointment of seeing each other so soon as
was expected will have a good effect on our minds,
as we are concerned to labour for strength to sink down
into holy resignation to the Divine will in all things;
from a persuasion that it remains to be our sanctification.
I confess I have often found it to be a hard lesson, and seldom, if ever,
more so than on the present occasion;
not only because I long to be released from this arduous field of labour,
where bonds and afflictions still await me, but also on account of our beloved son,
as I do not apprehend he can gain instruction in his line of business in London,
because the city air affects his health.

Since I began this, I have received yours of 4th mo.
3rd,
and the comfortable accounts contained therein have
been strengthening to my deeply tried mind.
I was glad to find that your mind was in measure prepared and preparing
to meet the disappointment which seems likely to occur,
except a retreat should be granted me in an unexpected hour.
I do tenderly sympathize with you in your lonely situation,
often looking at you "`as a sparrow alone on the house top;`" but then,
let us remember that not one of these was to fall without _his_ permission who numbers
the hairs of our heads;--and surely you are of more value than many sparrows.
Therefore I hope you will be preserved upon that foundation which stands sure;
not allowing this language to be formed in your mind, These are hard sayings,
who can bear them?
And then, though the enemy may at seasons come in like a flood,
yet the spirit of the Lord will lift up a standard against him.

I may inform you that I laid my case quite open to my friends in the select meeting;
informing them that notwithstanding I had no reason to expect
that I should be at liberty to return this season,
except I was excused from the greater part of what I then had in prospect,
yet I requested a few lines from that meeting,
in case I should see my way home before another Yearly Meeting; which was complied with,
and much was said to encourage me to faithfulness; which I esteem a singular favour,
and it is cause of thankfulness that way has been made for me in the minds of Friends.

[.signed-section-closing]
I remain your affectionate wife,

[.signed-section-signature]
Sarah Harrison.

--

8th mo.
8th. I have had between twenty and thirty meetings in London and its neighbourhood,
and we are to have one this afternoon in a gentleman`'s garden, at his request;
he and his family having attended several of our meetings,
he was so well satisfied that he sent to inform us that
if we inclined to have a meeting in his neighbourhood,
we should be welcome to his house, and if that was not large enough,
he had an adjoining lot that would hold a thousand people.
This proposal brought a heavy weight of exercise on my mind,
under which I waded for more than a week; and, after a sore conflict,
have concluded to attend it in company with dear William Savery,
who has been very brotherly to me,
and I never felt him nearer to my best life than since he has been in this city.
He is a dignified instrument indeed.

9th mo.
16th. We have had fifty-eight meetings since we left London,
which was five weeks yesterday; most of them were very large.
We have ten this week; so that it was thought best to rest today,
as I am very much relaxed, not having rested one day since we left the metropolis.

11th mo.
4th. We took our farewell of Norfolk about a week since, with joy;
having been six weeks closely engaged in that county.
The pure life is lamentably low in this part of the country;
and the conduct of many under our name so reproachful that the
way seemed to be very much closed in the minds of the people,
in some places where I felt the necessity of calling them together.
This has made hard work;
but I have thankfully to acknowledge that strength has been proportioned to the day,
and I have been helped along in a wonderful manner.

1st mo.
3rd, 1797.
We have now nearly accomplished our visit to all the meetings of Friends in England;
and I believe I shall be safe in saying,
that upon an average we have had three or four meetings
among those not professing with us,
for one among Friends; and mostly to good satisfaction: indeed,
I do not know that we have had one but what Friends and others were well satisfied with;
though I have found great difference at times among others as well as among ourselves.
On the whole,
I have abundant cause to reverence and adore that
great Arm of power that has hitherto supported me,
and opened a way for me where I saw no way;
neither was there any way for us to relieve our minds
but what he made in the hearts of the people.

Oh! how often have we been surrounded with the great men and women of this world,
who in the beginning of a meeting have seemed to look down upon us with
such unrighteous disdain as manifested the dispositions they were of;
and it would have cast down our minds below measure,
if we had not been clothed with that perfect love which casts out fear.
Yet, through mercy, before the meetings closed,
these same people have been so brought down, that when we came to part,
they seemed as if they could take us in their arms;
and many of this description have acknowledged their satisfaction,
I believe with true thankfulness of heart.
In many large towns where we have been under the necessity of having
two or three meetings before we could find our minds relieved,
they have not only increased in numbers, but in weight also;
and we have no reason to believe that the people
did not approve of the doctrine preached to them.
I mention these things to show how good the Lord has been to me, a poor pilgrim,
in a strange land;
and also to acknowledge the great willingness of Friends to assist me
in getting meetings appointed and providing places to hold them in;
and none more so than our esteemed friend James Wright,
who has been our acceptable companion for five months past.

2nd month 27th. We arrived at Tottenham, near London, the evening before last,
with the consoling evidence of having finished the work given us to do,
both among Friends and others, in those counties which remained unvisited last year;
and we have found it close work to accomplish it by this time,
having travelled hard all the winter when health would permit; which,
through mercy has been wonderfully preserved.
Indeed I have eat but little idle bread since I left my own habitation,
which is now almost five years.
And though some who have visited this land before me,
may not know how to account for my detention,
and perhaps may be ready to wonder how I have spent my time;
to whom I can answer with sincerity of heart, Not in doing my own will; but,
I humbly trust and believe, in doing the will of him that sent me.
Since I landed at Liverpool in the 8th month, 1792,
I have travelled about eleven thousand miles,
and had very many meetings among other societies; often two in a day.
And now,
on taking a retrospective view of my stepping along through this long and arduous journey,
the peaceful quiet that my mind is centred in,
is not only an ample compensation for all the trials, conflicts and baptisms,
which were no doubt necessary to prepare me for the work,--but
also a confirmation of the truth of that saying of the psalmist,
"`He that goes forth weeping, bearing precious seed,
shall doubtless return with rejoicing, bringing his sheaves with him.`"

4th mo.
8th. I had hoped to be at liberty soon to return to my native land,
but Scotland seems to be in my way.
I know that the increase of my bodily health should
be dedicated to the service of my divine Master:
for I must acknowledge he has an undoubted right to dispose of me as he pleases,
either in life or death.
And when I am led to consider how I spent the prime of my days,
and how long I stood in opposition to his holy requiring,
even after it was made known to me, I am like one in astonishment;
and being made a living witness of his unutterable condescension
in thus accepting of the refuse of my time,
and in consideration of the goodness and long-suffering
of God to me a poor unworthy creature,
my heart is at times humbled within me, and I am ready to say with one formerly,
If you will give me bread to eat, and raiment to put on,--be with me in the way I go,
and bring me back to my father`'s house, or to my native city, you shall be my God,
and I will follow you wherever you may see fit to lead me.

[.small-break]
'''

+++[+++After attending the Yearly Meeting in London, she went to Liverpool,
where she wrote to her husband as follows:]

[.embedded-content-document.letter]
--

[.salutation]
My dear husband,--

I once more take my pen to address you from this distant shore,
very contrary to my inclination or expectation when I wrote you last.
For at that time, as well as from the time we left London,
till we were within two days journey of this place,
I had indulged a hope that I should be set at liberty
to return with our beloved Samuel Emlen and son John;
and, if favoured to arrive safe,
to have the opportunity of conversing with you face to face;
which is abundantly more desirable to me than tongue or pen can express.

The first appearance of anything like a cloud over this pleasant prospect,
was occasioned by a dream, which was as follows:
I thought I went into a room where an old man was sitting in an arm-chair;
and as I entered the door, he seemed to fix his eyes upon me,
and addressed me in these words: "`You need not be in such a hurry to go to Liverpool,
to take your passage, except you do not intend to fulfill your promise.`"
I thought I asked what it was.
He said I had engaged to come to them;
and that I was also indebted to a people that lived upon the sea-shore.
I thought I remembered it well; and at the first was somewhat struck: but,
upon recollecting myself, thought I could with much truth say,
that when I promised I did intend to perform; but had been so closely engaged ever since,
that I had not been able; and now it was too late.
To which he made little or no reply.
Upon this I awoke, and seemed at first a good deal alarmed:
but then I considered it was but a dream; so went to sleep again,
and dreamed I had got home, and that things looked extremely unpleasant;
yet nevertheless, I thought I seemed glad I was there,
though I had only come to give up my old certificate,
and to get a new one in order to come back again
to visit those places which I had unwisely left.
At which, I thought you looked sorrowful,
and blamed me very much for coming home before I had done.

You may think these dreams awakened my feelings:
yet I was not disposed to lay any stress upon them,
or to turn my attention from the prospect of embarking with my dear friend:
neither did I, till after we had been on board the ship;
although dear Samuel Emlen had spoken the evening before,
in an opportunity which he had in Robert Benson`'s family,
with what may be called holy pertinence to my state; though he knew it not,
for I had not opened my mind to anyone.

A few hours after we returned from the ship, we set out for Lancashire Quarterly meeting,
in company with our much beloved friend Sarah Talbot, and her companion,
Sarah Shackleton; whose company was truly comfortable to me.
She had good service in some of the sittings of that meeting;
having grown much in her gift since I left home; in which I rejoice.
I was also favoured, through mercy, to relieve my mind once more among that people.
The following day, we had a large public meeting, which was thought to be a favoured time.
Next morning we parted with Sarah,
I trust under the influence of that love which first united our spirits together;
she proceeded northward, and we returned to Liverpool, taking one meeting in our way,
in hopes by throwing off this burden, I should have been easy to take my passage home.
But instead of that,
the prospect of Scotland came upon me with double
force;--yet I found no liberty to mention it,
even to my dear friend S. B. My beloved friend Samuel Emlen
was again baptized into the tried state of my mind,
and had to speak with such clearness to it,
that there was no need of further information.
Friends`' minds were all so dipped into sympathy with me
that inquiry was soon made into the cause of my uneasiness;
which I informed them of; and the select members being called together,
were led into full unity and near sympathy with me in the concern,
and they encouraged me to pursue my prospect of another visit to Scotland.

In that love which is stronger than death, my spirit salutes you,
and can bid you farewell, with heartfelt desires that the God of all grace,
mercy and peace may be with you, and comfort your mind under this fresh trial.

[.signed-section-signature]
Sarah Harrison.

--

On our way to Scotland, we again met with my much loved friend Sarah Talbot,
and her companion, which was cause of joy; more especially as our prospects were similar,
and it looked likely we might be together, at least part of the journey.
She is a powerful minister, and gets on finely.
We were at a number of meetings together, in which best help was graciously afforded;
so that we have great cause to commemorate the goodness of infinite Wisdom in
thus favouring us with the overshadowing wing of his love from place to place.

After leaving Liverpool, we had seventy-two meetings,
and travelled about eight hundred miles previous to our coming to Port Patrick in Scotland,
where we embarked for Ireland on the 5th of 10th mo.
1797, and landed after a passage of eight hours.

4th month 9th, 1798.
Have now nearly accomplished a second visit to this nation of Ireland,
and think my service is nearly complete.
I wish to embark for my native land, as soon as possible after my bands are loosed;
for I have often thought it not only unseemly,
but unsafe for those that are out on the Lord`'s
errands to stay longer than is really necessary,
after they have finished the work assigned them to do in any place.
This is what, I think, I have hitherto carefully avoided,
and am desirous of walking by the same rule to the end,
so that I may be preserved from erring in vision or stumbling in judgment,
with regard to my own movements; that if favoured to reach my own habitation,
it may be with an unclouded mind, and in the enjoyment of that true peace,
of which I have been so long in pursuit, and which I may with thankfulness acknowledge,
I have felt to flow as an uninterrupted stream since I came to this city, Dublin.

Liverpool, 5th mo.
14th. At the close of the Yearly Meeting in Dublin,
we sailed in company with William Savery and several other
Friends who were bound to the Yearly Meeting at London;
and landed in the evening at Holyhead, I trust with thankful hearts.
From there we proceeded to this place, and were kindly received by our mutual friends,
Robert and Sarah Benson.
My prospect is now to attend the Yearly Meeting in
London before embarking for my native land.

While in London, my way was entirely closed up from returning home with William Savery,
as I had anticipated.
So that my life seems to be a scene of conflict and probation; yet nevertheless,
when I am enabled to look toward that glorious habitation
whose walls are salvation and whose gates are praise,
and whose inhabitants can no more say they are sick,--there
is something so animating in the prospect,
that I have been made willing to endure hardness as a good soldier,
and to give up my own will and inclination, in obedience to the Divine requirings,
in order that I may happily attain to the enjoyment of it.
