== Chapter VI

[.letter-heading]
From Samuel Emlen

[.signed-section-context-open]
Warrington, 12th of 4th month, 1797.

[.salutation]
My dear friend, Sarah Harrison,--

You continue to be very much the companion of my mind,
though I have not so much proof as I could wish of your sisterly thoughtfulness about me;
who am desirous to be with all candour informed of your health and prospects of moving;
whether you have indeed expectations of returning
to our land soon after the Yearly Meeting,
or whether any other prospects arise, either of further detention in England,
or some other European country.
I believe you to have been abundantly favoured of our God,
and hope his continued mercy and support will be your rejoicing in all future trials,
as his ever worthy service is by you justly preferred
to all other claims on your time and attention.
He has indeed done much for you, and for me also.
At times of late I have had to sympathize with those humbled in soul,
who are ready to say with the holy apostle,
that "`to me who am less than the least of all saints is this grace given,
that I should preach among the Gentiles, the unsearchable riches of Christ.`"
But alas! the preaching within the pale of our own
society seems to be but to little purpose,
a very few instances excepted;
the times in which we live bearing a sad resemblance to those wherein it was asserted
"`every one of you runs to his own house;`" and many "`seek their own things,
but not the things that are Jesus Christ`'s.`" However if we can through holy help,
be enabled to deliver our own souls from condemnation,
this will be an unspeakable happiness worthy of all
care on our part to be established in;
let this consideration be encouragement to your own and dear Sarah Birkbeck`'s minds,
believing it is good to be patient and hope to the end,
as the coming of our Lord draws nigh.

My bodily powers are indeed greatly reduced; through difficulty and suffering,
I got here on second-day to the monthly meeting of ministers and elders,
and yesterday attended a large and more general monthly meeting;
in both which I was favoured with renewed confirmation
that our good Lord and Master has not rejected me,
neither withheld the offers of continued compassion for the recovery and
help of many who have not sought him with that solicitude of soul,
which an establishment in his lovingkindness and protection loudly calls for.

I have sometimes looked towards a journey to London,
with desires to be among the brethren and sisters at the ensuing annual solemnity;
but riding even in post chaise, is so very distressing to me,
that at times I much doubt whether I shall be able to accomplish so long a journey.
Every heart knows its own bitterness,
but I believe very few are sensible of the pain and sufferings
I endure in moving about from place to place.

Give my love to Sarah Birkbeck and to your son John 1 wish he may be much
exercised in watchfulness and care for preservation from evil,
among the multiplied temptations I suppose him surrounded with in his present movements,
in the pursuit of that knowledge for which he left
his native country to become more proficient;
this ought not to be the primary object of solicitude,
but that God in all things may be glorified and the Truth exalted,
through a humble obedience to the law and the testimony inwardly revealed;
notwithstanding he may thereby become a wonder to many through his own abasement,
even as to dust and ashes.
They that honour God will be honoured by him;
but they that neglect and despise the holy commandment
shall be lightly esteemed in the awful day of decision,
when there will be a discrimination made between those that
have served God and those that have not served him.

I have no letter from America written since this year began.
I wish to know your latest dates from there,
with what tidings you may be free to communicate,
especially if anything be told you respecting my dear children.
I long particularly to hear of my beloved daughter`'s religious improvement;
such an account would make me joyful even to the offering of thanksgiving
and praise unto Him whom I wish ever to serve in the gospel of his Son.
My love to Thomas Scattergood--I want to know how and where he is employed,
and whether he has any prospect of going home this summer.
Is there any tidings of George Dillwyn and his wife, of David Sands and William Savery?
Do you know where Joshua Gilpin and James Fisher are?
Do you know when Charity Cook of Carolina, and Hannah Barnard of New York government,
are expected?
I am now at the house of our kind friends John Bludwick and wife,
who unite in kind love to you and Sarah Birkbeck.
Direct soon to the care of R. Benson, Liverpool, for your affectionate friend,

[.signed-section-signature]
Samuel Emlen

[.letter-heading]
From Margaret Allen

[.signed-section-context-open]
Hoe-mill, Essex, 8th of 6th mo.
1798.

[.salutation]
Beloved friend, Sarah Harrison,--

I have frequently regretted the little opportunity
that has fallen to my lot of enjoying your company,
or that of your fellow-labourers from your land.
How gladly would I have divided with them the outward blessings of food, drink,
and lodging;
but ah me! this gratification I have been deprived
of,-- which has sometimes forced from me,
in the bitterness of my spirit, a language similar to this, "`Woe is me,
that I sojourn in Mesech, and dwell in the tents of Kedar.`"
Although this is my mournful lot that I have to abide in,
it has not prevented the flowing of near and dear sympathetic feelings
towards you and them,--even feelings too deep to be uttered by me in words,
and only to be felt, as deep calling unto deep.
May the everlasting arms of Omnipotence surround you,
and bear up your drooping spirit above both the inward and outward
billows that may be permitted to roll round your tabernacle,
for the further trying and strengthening of your faith and patience.

When I have looked at your debilitated state of health,
and the travail and labour that you have been enabled to pass through,--it
has raised in my mind a tribute of praise to Him,
who has been pleased to manifest his strength in your outward weakness.--Surely
it is his own works alone that ever did and ever will praise him.
He is pleased in this day to make use of the weak things of this
world to confound the wisdom of the seeming wise,--and what for?
that no flesh may have to glory.
And I do believe he will more and more bring to nothing
the counsel of the seemingly prudent,--those who are often
darkening right counsel with words without the divine knowledge,
and meddling with things too high for them, and too deep for their own wisdom to fathom.

Well, my beloved friend,
may you in time to come have to look back on the
many rough places that you have had to pass through,
for the opening of that long unfrequented path,--from
the family to the people;--a path almost closed up,
and briars and thorns in some spots hedging it up more closely;
and with David have to acknowledge, "`by you have I run through a troop,
by your might have I leaped over a wall.`"
This, my dear friend, I doubt not will be your joyful experience,
and the crown of your rejoicing,
at a time when all outward things will stand in no stead.
Then, Oh! then, may you look back on all the trials of your pilgrimage,
and bid a final farewell to all your conflicts,
and have forever to join the spirits of those that have come through many tribulations,
and had their garments washed and made white in the blood of the Lamb.
This is the sure reward of those that have not counted their lives dear to them in comparison
of the love of God in Christ Jesus,--of which happy number is my beloved friend;
and that she may be preserved so through time,
is the present breathing of her that can truly subscribe herself your affectionate friend,

[.signed-section-signature]
Margaret Allen.

[.postscript]
====

P+++.+++ S. I should, if my life is lengthened, be truly glad to have a few lines from you;
I don`'t care how they are written, if I can but read them.
This is written with a trembling hand, and an aching head.
My health is in a poor, and I apprehend,
declining state,--but I am favoured to feel at times a sweet calm,
and something like a hope that all the conflicts of my day will work together for good;
and that when the All-wise may see fit to say, It is enough, my poor, tried,
exercised spirit will be at rest.
This little gleam of hope is at times graciously lent,
and is to me more than I at one time ever expected.
Once more farewell, dearly beloved friend,

====

[.signed-section-signature]
Margaret Allen

[.letter-heading]
From George Dillwyn

[.signed-section-context-open]
London, 9th mo.
28th, 1798.

[.salutation]
My dear friend,--

I have now before me your letter begun 8th mo.
25th, at Minden, and ended the 3rd of this month at Pyrmont.
It came to hand the 27th,
and brought my mind into a deep degree of sympathy with you and
your companions--deeper perhaps than I could have felt,
if I had not been exercised in the same track of mortifying conflicts.
I endeavoured, you may remember, to prepare you for it before we parted;
// lint-disable modernize-words "possess you"
though I well knew nothing but experience could fully possess you of my meaning;
nor can I even now expect,
that anything I can offer will be answerable to your exigencies,
and take off the nausea of that bitter cup which
Divine wisdom has seen fitting to allot you.
There is no help, under such almost inexplicable difficulty,
but in Him who knows and feels our infirmities of every kind,
and is both able and willing to succour and relieve,
as we bespeak his merciful attention to us,
by labouring after a total surrender of ourselves and our all to his disposal.--This,
you may say, is easy, when his sustaining arm is sensibly felt to be underneath.
"`Does the ox low over its fodder?
or does the wild donkey bray when it has grass?`"
but, "`Can that which is unsavoury be eaten without salt;
or is there any taste in the white of an egg?`"

Ah, my dear Sarah, I can feel for you,
and you see I can talk of these things like a man of understanding; but,
when I was exposed to them,
I thought myself less than the least of all in the practice of the great duty of resignation.
Yet I am convinced it is an attainment worth aspiring and pressing after,
although the more we do so, the further we may seem to ourselves to be from it.
For the believing because we see,
is not the only degree of faith which commends us to Divine favour;
but "`blessed (said Christ) are they that have not seen, and yet have believed.`"
Let us then endeavour to possess our souls in patient submission to the will of God;
and where we can`'t unravel, learn to trust;
and also when favoured with a discovery of his good pleasure,
above all to be careful that on no consideration whatever we presume to indulge
a wish that he may alter his mind in favour of our natural choice and inclination:
believing that if we are prepared to hear the salutation of his voice,
it will be sweet as ever,
and that there will be "`a performance of those things
which have been told us of the Lord,`" in his time.

It will, I doubt not,
afford you and your dear companions a degree of comfort to be informed,
that at our late Quarterly meeting (the 25th of this month) the spirit
of supplication was poured forth on the assembly in your behalf;
and that the persuasion of its availing acceptance with him who inspired it,
remains with lively impression on my mind while I am writing!

I note what you have mentioned of your interruption at Minden;
and am not at all surprised at it.--Our similar one at Hanover,
convinced me that the progress of such a peculiar testimony as ours is,
cannot reasonably be hoped for in any other way;
and that all things of that kind would be rendered subservient to the great end in view,
and the furtherance of the gospel in this new field of labour.
Without fiery baptisms, we should not be equal to such engagements,
but our spirits would be within the reach of opposers,
and they more than a match for us on their own ground: for there,
what are sheep to wolves, and doves to serpents?

Mary Stacey has been out of town (in Hampshire, Berkshire, etc.) some time,
so that the other particulars of your fare at Minden, I am not yet acquainted with;
and when the opportunity will be afforded me I know not,
as I propose going tomorrow into Kent, on the Yearly Meeting appointment.
Mary, in writing to dear George,
will probably have informed you of the sorrowful intelligence from our dear Philadelphia,
that the yellow fever has been again permitted to visit its inhabitants, who, as before,
were going into the country-places around.
On the 10th of the 8th mo.
the board of health there reported that from the 1st, eighty-two persons had died,
and twelve were sent to the hospital.
It appeared nearly where it did the first time, in Water street above Arch street,
and was chiefly confined to that neighbourhood.
We anxiously wait for further particulars.
How many mementos do we meet with,
of the uncertainty of all sublunary possessions and enjoyments!
Happy they who are above all things concerned to fulfill the duty of their day,
and meet the awful messenger at the stations assigned them!

My Sarah Dillwyn as well as myself, has often looked after you with tender solicitude,
and now desires to join me in this expression of it.
We are pleased with the remembrance of our Pyrmont friends,
and wish their prosperity in the ever-blessed Truth,
as the only foundation on which we can safely trust for peace here,
and happiness hereafter.
Please to communicate our love to all of them who retain their integrity,
as opportunity and liberty occur.
Indeed, though I am addressing you as if you were at Pyrmont,
it seems not very reasonable to suppose the company is still detained there.
I however propose forwarding my letter to Hamburg,
and leave the further direction to William Wood and company,
whom you will no doubt furnish with an account of your movements.

Sarah Talbot and Phebe Speakman are, I believe,
in the western counties--Hannah Barnard and Elizabeth
Coggeshall have been at the Scilly Islands,
and I suppose are now in Cornwall--Thomas Scattergood
continues hereaway--mostly at Tottenham.
I may add, if it will give you any satisfaction,
that G. and S. D. are not likely to take their leave
of this country before you return to London:
so that there is a possibility, if you don`'t stay away too long,
that they may be your shipmates.
But whether so or not, they are willing to be your sympathizing companions,
in the exercise of patient hope and humble dependance, that,
when these earthly voyages and journeys terminate, we may be favoured,
through boundless and unmerited mercy,
to meet on that happy shore which cannot be disturbed by any of
the troubles which beset us in this world of vicissitude!
In much affection to you all, (in which my Sarah Dillwyn joins) I remain,
your friend and brother,

[.signed-section-signature]
George Dillwyn.

[.letter-heading]
From Rebecca Jones

[.signed-section-context-open]
Edgley Farm, 10th mo.
23rd, 1798.

[.salutation]
My endeared sister, Sarah Harrison,--

Your beloved husband having imparted to me the contents of your letter,
giving the unlooked for intelligence of your prospect of a visit to France and Germany,
my mind is so dipped into sisterly sympathy with you under the trial,
and with dear Thomas under the disappointment,
that I have taken up my pen once more to salute you,
and to manifest my near unity being continued under your varied exercises,
and in this in an especial manner.
May you hold out steadfastly unto the end of your service, in faith and patience,
that so you may indeed reap a "`full reward`" for the "`whole
day`'s work`" which you are called to perform,
that so your return may be in the Lord`'s time,
with unshaken peace,--is my fervent prayer for you.
I could enter deeply into your feelings,
with respect to a separation (of body only) from your companion,
that dear sweet-spirited disciple Sarah Birkbeck, who having,
like the younger prophet formerly, poured water on the hands of a mother in Israel,
will undoubtedly share with you in spirit in the reward of entire faithfulness.
Dear Charity Cook and Mary Swett being yoked with you, reminds me of what Solomon says,
"`a threefold cord is not easily broken`"--and the assistance
of one or more of those brethren whom you have mentioned,
must be a strength and comfort to you and them; please give my love to them all.
May the good hand which has conducted others before you,
be with and carry you safely and sweetly through
all the labour and trials that may attend you,
and bring you back with sheaves of peace, says my soul.

I expect your husband and children will furnish you with an account of
the renewed dispensation of sickness and mortality to our poor city,
to New York, Wilmington,
etc. so that my feelings may be spared from a recital of the varied
conflicts and exercises which we have had to sustain.
But Oh! my dear friend,
what a large vacancy is made in our militant church by so many being translated therefrom,
and gloriously added to the church triumphant in Heaven!
The subject is too much for me to enlarge upon; I shall therefore proceed to mention,
that all the families of our dear American friends now in Europe, so far as I know,
have been preserved alive during the late pestilence,
and at present are all in reasonable health;
except that dear Sarah Scattergood has buried her eldest daughter,
a fine girl about fourteen years of age; which, with other interesting intelligence,
is forwarded to her dear husband.
He appears to be deeply tried, and in bonds in the great metropolis;
may his good Master be pleased to loosen his cords, and once more set him at liberty,
is my desire for him.

Having heard of the safe arrival of dear William Savery at New York,
we are in hourly expectation of once more taking
him by the hand;--and so I trust in the Lord`'s time,
we shall you and our other absent friends, to all of whom is my dear love.
I saw your husband last first-day at Germantown.
He appeared well and easy in mind--and with your children has been there
some time:--you will understand that I also am out of our poor,
infected city, and at the hospitable mansion of my old kind friend, Katherine Howell.
I left my own habitation early in the 8th month,
just as the fever began to make its appearance,
and went to the Quarterly meetings of Rahway and Burlington,--which being over,
I did not see my way clear to return to the city;--so between
these places spent the time till about two weeks ago,
when I came here; and now, as we learn the disease is abating,
am waiting until it may be safe to return.
Your kinsfolk, dear L. and J. Snowdon, have stayed in the city,
and been mercifully spared to the comfort of the little remnant that were in it.
Our large meetinghouses have been kept open,
and sometimes the number that met in them has not exceeded twenty
to forty! by which you may judge a little of the state of the whole.
Our dear friend Mary Pryor, who has been brought to us by a miracle,
I understand has in prospect to return to her own land after our adjourned Yearly Meeting,
which is to be held in the next 12th month.
She has had acceptable service in this land, and so has our dear friend Jarvis Johnson,
who has been absent from us travelling to the southward
about a year--they both enjoy good health.

May the Shepherd of Israel who put you forth,
be with you in every trial,--make your way prosperous in
his work,--reward your dedication with soul enriching peace,
and, if consistent with his blessed will,
bring you back in safety to your beloved relations and friends,
is the fervent desire of your exercised and tribulated sister,

[.signed-section-signature]
Rebecca Jones.

[.letter-heading]
From Deborah Darby

[.signed-section-context-open]
Colebrookdale, 1st mo.
28th, 1799.

[.salutation]
Beloved friend, Sarah Harrison,--

Although I feel myself poor, and stripped,
and not likely to convey anything worthy your acceptance,
yet I wish to manifest the sympathy and near fellowship I have with you,--remembering
that as the prophet was fed by ravens,--so sometimes the expression of regard
may tend to the encouragement even of those that were in Christ before me.

I can truly say when the tidings reached my dear Rebecca Young and myself,
of your way being closed, as to a return to your native land,
and your feet turned into Germany,
we felt deeply with you in those baptisms you were necessarily introduced into;
yet secretly rejoiced that you were made willing
to go again into the arduous field of labour,
not doubting this act of dedication contributing to your experiencing on your own behalf,
that "`the wise shall shine as the brightness of the firmament,
and those that turn many to righteousness as the
stars forever and ever;`" and that through your labours,
the solitary in families would be made to rejoice,
and thus there would be ability-to withstand in the evil day, and having done _all,_
to _stand._

And now, my beloved friend, if you apprehend your labour nearly finished in this land,
and can feel liberty to rest a little under our roof,
it would be a great satisfaction to my dear sister M. Rathbone, as well as to myself;
and if you can see your way thus to gratify us,
and will give us information of the time of your coming,
we will meet you either at Birmingham or Worcester, whichever you may choose to appoint.

My dear companion and myself have been returned from
an exercising journey in the northern counties,
about two weeks.
She is now at Shrewsbury, or would unite in the expressions of much regard for you.
I expect her with me in a few days; for we think it a favour to have her with us,
when a little rest is granted.
We have had many late letters from our beloved friends
in America--the last from Catharine Hartshorne,
giving a pleasant account of health being restored in your native city,
and all things going on much as before the sickness.
She desired to be affectionately remembered to you and her other friends,
now ambassadors to this favoured land.
She says Mary Pryor and Elizabeth Foulke were then visiting Chester county,
and well--as were your different connections.
I unite in near remembrance of Thomas Scattergood, Charity Cook, Mary Swett,
Sarah Talbot, or any of your dear country folks that may fall in your way;
all of whom we wish to consider this house as one of their homes while in this country.

Farewell, my dear friend.
May the Lord often refresh your spirit,
and enable you to set up your Ebenezer to his praise,
who has made you a blessing to many.
Accept the united affectionate love of all my connections here,
and believe me to remain your sincere friend,

[.signed-section-signature]
Deborah Darby.

[.letter-heading]
From Mary Naftel

[.signed-section-context-open]
Guernsey, 22nd of 5th mo.
1799.

[.salutation]
My beloved friend,--

An opportunity presenting for conveying a few lines,
and not knowing but it may be the last before you leave England,
I was willing to embrace it;
if only to send the remembrance of my dear love which has been often raised,
and still lives in my heart for and towards you,
with desires for your safe guidance through the intricate, winding,
exercised path that I believe you have to tread in beyond many,
and I suppose somewhat contrary to your own views and expectations.
But what of that?
It`'s no matter how difficult the path may have been, or may now seem to be,
if patience and perseverance are but afforded to keep therein the appointed season.
I think, for my part,
I generally feel most unity with those that are led a little out of the common line;
not merely (I hope) from a liking of anything of that kind,
but because I think the state of the church requires it: and as we, as a society,
come more and more out of formality and a dependance one upon another,
it will I expect become more the case, that our exercises will be more apart,
and perhaps in some respects different one from another.

As for myself, the comparison to an owl in the desert, or a sparrow upon the house-top,
is most fitly mine: but I desire contentment,
and am sometimes favoured with it to my own admiration,
and to feel something of a calm or quietness of mind, which, at times,
I am ready to fear I may too much rest in,
like a cessation from exercise on account of others;
except now and then occasional or apparently accidental opportunities occur.
But to labour after a resigned mind seems all that is necessary,
either to be or not to be employed in the Lord`'s work.
I write in freedom to you, my dear friend,
having very few to commune with;--no father or mother,
in the spiritual import of the word;
and I am ready to apprehend I may never see you more.

The visit of your beloved countrywoman, Sarah Talbot, with her companions,
was truly acceptable to us; and you both remain to be near and dear,
even as epistles written on my heart,
so that at seasons I think neither time nor distance will ever erase the impression.
I continue to feel a solicitude on account of my
beloved friends thus engaged in the work,
who have gone as with their lives in their hands,
and have been and are as pilgrims and strangers in the earth;
not counting their lives dear unto themselves,
that so like the good apostle they may finish their course with joy.
I have no doubt, as there is a faithful continuance herein,
that this will be your happy experience at last,
whatever may yet be your allotted probations.

I desire to be remembered by you in your solemn awful
approaches before the invisible I AM,
in secret as well as public.
I partake, I think, in part with you now assembled at Yearly Meeting,
trusting that Divine help is and will be near to favour you together
with those streams of refreshment that come from his presence,
in which there truly is life,
and a remnant who are sensible of it cannot but praise him therefor.
These he will preserve,
as they keep near unto him in lowliness of mind and in singleness of heart,
both in heights and in depths; yes,
though they may walk as in the valley and shadow of death, they shall see no evil.
Ah! my beloveds, my heart is enlarged towards you in tender love.
Look not out; fear not man;
nor depend at all upon man whose breath is but in his nostrils,
for wherein is he to be accounted of?
For so it is, when we look too much that way,
it may be permitted that we may be the more tried
in order to wean us from all outward dependance.

With endeared love, in which my husband joins, I conclude,
and am your truly affectionate friend,

[.signed-section-signature]
Mary Naftel.

[.letter-heading]
From Martha Routh

[.signed-section-context-open]
Manchester, 8th mo.
11th, 1806.

[.salutation]
My dear friend,--

Be assured whether I speak or keep silence,
you are often near in remembrance in the fellowship of suffering,
when "`deep calls unto deep,`" and all the billows pass over us;
yet under any of these dispensations, let our prayers still be to the God of our lives,
that he may sanctify every affliction, and make us pure by these fiery trials,
whether they arise from within or without,
or whether the wounds we receive may be from the hand of an enemy,
or in the house of our friends.
He that is mighty can do great things and work deliverance in his own time,
when our finite conceptions may see healing virtue as at a great distance.
But how encouraging it is to believe that in all our afflictions he is afflicted,
and the angel of his presence encamps round about us!
Was it not for his invisible hand, which, however hiddenly, is stretched out still,
where, my beloved sister in tribulation, should you and I have been before this day?
Should we have been in the land of the living?
Let us then thank our God and take courage;
for though two seas should yet meet and the vessel thereby become a wreck,
or the poor tabernacle fall in the combat,
yet the life that is hid with Christ in God cannot be lost,
but will live to praise and celebrate his name who is worthy now and forever.

The account my dear E. F. gives of your state,
with that of our dear and worthy friends James and Phebe Pemberton,
and our honorable brother Samuel Smith,
likewise that our dear elder brother David Bacon was in poor health,--so
wrought upon my feelings that I verily thought,
if I had wings like a dove,
the strength of best love and fellowship would urge
my flight to speak comfortably to you.
But is not, my endeared friends, your God, my God; and your Father, my Father,
who is everywhere present, and I feel a humble trust has you in his safe keeping,
and will be your all in all in the needful time.

I am sorry that one pang should be occasioned to any of them by not hearing from me,
and feel much concerned that captain Hathaway was not arrived,
by whom I addressed dear Samuel Smith, Phebe Pemberton, and Elizabeth Foulke,
pretty fully, and Phebe again from London soon after the Yearly Meeting,
and her husband about two weeks since, from Liverpool.
And indeed I think my right hand must forget its use, or my tongue cease to speak,
if I forget my dear friends on your side the water; whom to have lived or died with,
would have been my own choice, rather than to have again crossed the mighty deeps.
Yet there are a few little ones in my native land, and also in this meeting,
who are as bone of my bone in the spiritual kindred;
for their sakes I am willing to be a sojourner the appointed season of unerring wisdom,
or I sometimes think, it might be better for me to die than to live,
lest I should not hold out to the end in well doing.
After our Yearly Meeting I was about three weeks in Essex,
where affectionate inquiry was made after you.
It is likely you will have heard that dear Mary Pryor
is gone on a religious visit to some parts of Ireland,
manifesting dedication in advanced age worthy of consideration.
I think I never heard her more close or lively in
testimony than in our last Yearly Meeting.

I hope to forward this to Liverpool tomorrow,
and should it get safe to hand request you to present me in near and dear
affection to the friends mentioned herein,--also to dear Ann Mifflin,
whose letter I have also received; to your aged brother, if living, and his children,
whom I love in the truth; likewise your husband, with any others in your freedom;
as I have not room to mention many more, must not forget dear Rebecca Jones,
Thomas Scattergood, and others of our fellow-labourers.

[.signed-section-signature]
Martha Routh.

[.letter-heading]
From the Same

[.signed-section-context-open]
Manchester, 7th mo.
2nd, 1810.

[.salutation]
My dear friend,--

I have long desired I might not outlive the season
when I might be capable of feeling a sympathizing mind;
and I now believe that prayer will be granted to me while I have a being here.
Under this impression, my spirit has often visited you, since our lately deceased friend,
Mary Gilbert,
informed me of the renewed trial which you and your husband
were brought under through loss of outward property;
and though I do not esteem this the greatest trial to a redeemed mind, no,
my beloved friend,
we have known much deeper wounds than anything arising
from this quarter;--yet in advanced age,
this also must be nearly felt.
But what a favour, under all that is permitted to befall us,
that we know him in whom we have believed,
and that we can spread our cause on his sacred altar,
and leave it with him both to judge and to plead.

It is grateful to hear by a letter from our endeared sister in tribulation,
Phebe Pemberton, that your husband and yourself can remain in your habitation,
and with some additional labour pass on comfortably.
The last letter I received from our nearly united, and justly beloved fellow-labourer,
Deborah Darby, says, "`the receipt of yours, written last month,
was cordial to my feelings as the salutation of an endeared sister,
as also the intelligence respecting our dear friends in America;
except the account of the increased afflictions of dear Sarah Harrison,
which will doubtless affect the minds of many of her friends with near sympathy:
but she has long known the name of the Lord to be a strong tower,
to which she has fled and found safety;
and there is no doubt that this place of refuge will be renewedly opened to her consolation.`"
We were companions together about three weeks at the close of a western journey,
in the 10th month of 1808.
Mary Jefferies had been with her, and Ann Grace of Bristol with me,
and our way lying together homewards,
we mutually embraced each other in the fellowship of the gospel,
which bound us in the cement of that union, which I trust will never be dissolved;
though my feelings were then deeply penetrated with an apprehension
that she would not be long in the field of labour;
her bodily strength being so reduced that she could not
well rise from her bed without a little assistance,
nor did she seem much refreshed by the sleep she got.
But she is now gone from all trial, beyond temptation, and above applause;
and her soul no doubt centred where the morning stars sing together,
and the sons of God shout for joy.

Perhaps you will have heard that Edmund Darby was suddenly removed,
a few weeks after his dear mother.
He was going with his wife to attend the marriage of one of her brothers,
near Bristol,--was taken ill on the road with pain in his bowels,
and died at his uncle Robert Fowler`'s, at Melksham, where his remains were interred.
William Byrd and his wife attended the burial,
who with others concerned in gospel mission,
expressed a belief that he was taken in mercy, and entered into rest.
Deep instruction to us who survive,
is no doubt intended by the all-wise Disposer of events,
when the young and the rich in this world are so suddenly called from works to rewards.

Dear Mary Alexander died at Worcester of the small-pox,
in a resigned sweet state of mind,
according to the testimony read at our Yearly Meeting.--Great indeed is
the stripping we have had for two years past of this part of the family:
and now dear John Hall, with several others,
are numbered to the silent grave within the last three months.
John Hall was taken with a violent bleeding at his nose,
the day I was at their meeting at Broughton, so that he could not attend;
but in the evening appeared very serene, and sweetly revived that passage of scripture,
"`as iron sharpens iron,
so does a man the countenance of his friend;`" and said
he thought he had never felt the truth of it more forcibly.
He has left ten children, several married, and the rest appeared hopeful.

Please to present me in near affection to your husband, nephew and nieces,
with any other friends in your freedom, and accept for yourself a large portion;
in all which my husband unites with your sincerely affectionate friend,

[.signed-section-signature]
Martha Routh.

[.letter-heading]
From Thomas Scattergood

[.signed-section-context-open]
New York, 6th mo.
11th, 1811.

[.salutation]
Dear Sarah Harrison,--

Having received the enclosed
in a valuable letter from Elizabeth Ussher of Ireland,
I thought it afforded an opportunity to write a few lines and enclose it to you.
I felt the more induced to make the attempt,
from the remembrance of my two last visits to you, O you exercised, dear friend,
whose path through life has not been strewed with roses,
but ofttimes and again as with prickly thorns.
Well, I may say again to you, what matter,
if so be those slight afflictions work for you a
more exceeding and eternal weight of glory,
by patiently continuing the warfare in righteousness;--for surely
the blessed Shepherd and Bishop of our souls knows how much is
right for us to bear in order to fill up the measure.
Oh! then, that your tribulations may work in you patience; and patience,
yet greater experience of the love and mercy of your heavenly Father,
to be shed abroad in your heart in due time:--fear not,
nor doubt that this is possible with Him with whom all things are possible;
who can bring light out of darkness, strength out of weakness,
and cause you yet livingly to acknowledge that you
could not have done without your afflictions.

Tell your dear Thomas from me (when you think it right) as one
that has loved and sympathized with him for years in his afflictions,
(for he has been afflicted) not to give up the conflict or warfare.
Oh! that he could and would stand still for a little moment,
and wait for the salvation of his God,--his merciful and compassionate God,
who is able to help him through all, even unto the end of time,
and grant him an inheritance among those who have passed through great tribulations.
Tell him in all straits to sink down and wait upon his God for help, and look not,
neither depend on anything short of his almighty Arm for strength and preservation.
Thus will he surmount those mountains of difficulty that have appeared in the way; yes,
in due time, he will know the "`mountains and the hills also to break forth into singing,
and all the trees of the field to clap their hands.
Instead of the thorn will come up the fir tree,
and instead of the brier will come up the myrtle tree;
and it shall be unto the Lord for a name,
for an everlasting sign that shall not be cut off.`"
Thus desires, thus prays for you, my poor, dear,
tribulated friends (hoping you may yet behold with your eyes days of greater calm,
peace and comfort) your affectionate friend,

[.signed-section-signature]
Thomas Scattergood.
